(() => {
  'use strict';
  const SUPABASE_URL='https://ahoejwyxfclndcbcxhwv.supabase.co',SUPABASE_KEY='sb_publishable_FeyV-yXT6lwFHh737rYnAQ_mYoP8TIW';
  const byId=id=>document.getElementById(id),itemByKey=(items,key)=>items.find(item=>item.item_key===key);
  const safeUrl=value=>{const url=String(value||'').trim();if(!url)return'';if(/^(#|mailto:|tel:)/i.test(url))return url;try{const parsed=new URL(url,location.href);return['http:','https:'].includes(parsed.protocol)?parsed.href:'';}catch(_){return'';}};
  const applyTextStyle=(element,style={},prefix='')=>{if(!element)return;const size=Number(style[`${prefix}font_size`]),color=style[`${prefix}color`];if(size>=10&&size<=120)element.style.fontSize=`${size}px`;else element.style.removeProperty('font-size');if(/^#[0-9a-f]{6}$/i.test(color||''))element.style.color=color;else element.style.removeProperty('color');};
  const identify=(element,item,field)=>{if(!element||!item)return;element.dataset.homeId=item._draftId||item.id||item.item_key||'';element.dataset.homeField=field;};
  function makeLink(item,className='link'){const url=safeUrl(item.url);if(!url)return null;const link=document.createElement('a');link.className=className;link.href=url;link.textContent=item.link_label||item.title;if(item.open_new_tab){link.target='_blank';link.rel='noopener';}identify(link,item,item.item_type==='link'?'title':'link_label');applyTextStyle(link,item.style_data);return link;}
  function applyHero(items){const eyebrow=itemByKey(items,'hero_eyebrow'),title=itemByKey(items,'hero_title'),accent=itemByKey(items,'hero_accent'),body=itemByKey(items,'hero_body'),button=itemByKey(items,'hero_button');const set=(id,item,field='title')=>{const el=byId(id);if(!el||!item)return;el.textContent=item[field]||'';identify(el,item,field);applyTextStyle(el,item.style_data);};set('homeHeroEyebrow',eyebrow);set('homeHeroTitle',title);set('homeHeroSubtitle',title,'body');set('homeHeroAccent',accent);set('homeHeroBody',body);if(button){const el=byId('homeHeroButton'),url=safeUrl(button.url);el.textContent=button.title||'Learn More';if(url)el.href=url;el.hidden=!url;identify(el,button,'title');applyTextStyle(el,button.style_data);}}
  function applyCardStyle(card,item){const style=item.style_data||{},span=Math.max(1,Math.min(5,Number(style.width)||1)),height=Math.max(0,Math.min(800,Number(style.min_height)||0));card.style.setProperty('--home-span',span);if(height)card.style.minHeight=`${height}px`;else card.style.removeProperty('min-height');card.dataset.homeId=item._draftId||item.id||'';card.dataset.homeSection=item.section_key;card.dataset.homeActive=item.active===false?'false':'true';}
  function renderFeatures(items){const target=byId('homeFeatures'),rows=items.filter(x=>x.item_type==='card'&&x.section_key==='features');if(!target||!rows.length)return;target.replaceChildren(...rows.map(item=>{const row=document.createElement('div');row.className='feature';applyCardStyle(row,item);const icon=document.createElement('div');icon.className='icon';icon.textContent=item.icon||'◆';identify(icon,item,'icon');const copy=document.createElement('div'),title=document.createElement('b'),body=document.createElement('small');title.textContent=item.title;body.textContent=item.body||'';identify(title,item,'title');identify(body,item,'body');applyTextStyle(title,item.style_data,'title_');applyTextStyle(body,item.style_data,'body_');copy.append(title,body);row.append(icon,copy);return row;}));target.style.gridTemplateColumns=`repeat(${Math.min(rows.length,5)},minmax(0,1fr))`;}
  function makeCard(item,tile=false){const card=document.createElement('article');card.className=tile?'tile':'card';applyCardStyle(card,item);if(item.icon){const icon=document.createElement('div');icon.className=tile?'bigicon':'card-icon';icon.textContent=item.icon;identify(icon,item,'icon');card.appendChild(icon);}const heading=document.createElement(tile?'h4':'h3');heading.textContent=item.title;identify(heading,item,'title');applyTextStyle(heading,item.style_data,'title_');card.appendChild(heading);if(item.body!=null){const body=document.createElement('p');body.textContent=item.body||'';identify(body,item,'body');applyTextStyle(body,item.style_data,'body_');card.appendChild(body);}const link=makeLink(item,tile?'mini-btn':'link');if(link)card.appendChild(link);return card;}
  function renderCards(items,section,targetId,tile=false){const target=targetId==='documents'?document.querySelector('section.documents-section#documents'):byId(targetId),rows=items.filter(x=>x.item_type==='card'&&x.section_key===section);if(!rows.length||!target)return;const cards=rows.map(x=>makeCard(x,tile));if(section==='resources'){target.querySelectorAll('[data-home-section="resources"]').forEach(x=>x.remove());target.append(...cards);}else target.replaceChildren(...cards);}
  function renderNavigation(items){const target=byId('homeNavigation'),rows=items.filter(x=>x.item_type==='link'&&x.section_key==='navigation'),links=rows.map(x=>makeLink(x,'')).filter(Boolean);if(!target||!links.length)return;target.replaceChildren(...links);links[0].classList.add('active');}
  function freeform(items,device,{initialize=false}={}){
    const page=document.querySelector('.page'),cards=[...document.querySelectorAll('[data-home-section]')];if(!page||!cards.length)return false;
    const pageRect=page.getBoundingClientRect(),flowHeight=Math.max(page.scrollHeight,document.documentElement.scrollHeight);let hasLayout=false;
    cards.forEach((card,index)=>{const item=items.find(x=>(x._draftId||x.id)===card.dataset.homeId);if(!item)return;item.style_data=item.style_data||{};item.style_data.layouts=item.style_data.layouts||{};let layout=item.style_data.layouts[device];if(!layout&&initialize){const rect=card.getBoundingClientRect();layout={x:Math.round(rect.left-pageRect.left),y:Math.round(rect.top-pageRect.top),width:Math.round(rect.width),height:Math.round(rect.height),z:index+10};item.style_data.layouts[device]=layout;}if(layout)hasLayout=true;});
    if(!hasLayout)return false;let layer=byId('homeFreeformLayer');if(layer)layer.remove();layer=document.createElement('div');layer.id='homeFreeformLayer';layer.className='home-freeform-layer';page.appendChild(layer);let bottom=flowHeight;
    cards.forEach(card=>{const item=items.find(x=>(x._draftId||x.id)===card.dataset.homeId),layout=item?.style_data?.layouts?.[device];if(!layout)return;card.style.position='absolute';card.style.left=`${Math.max(0,Number(layout.x)||0)}px`;card.style.top=`${Math.max(0,Number(layout.y)||0)}px`;card.style.width=`${Math.max(90,Number(layout.width)||card.offsetWidth)}px`;card.style.height=`${Math.max(55,Number(layout.height)||card.offsetHeight)}px`;card.style.minHeight='0';card.style.zIndex=String(Number(layout.z)||10);card.style.overflow='auto';layer.appendChild(card);bottom=Math.max(bottom,(Number(layout.y)||0)+(Number(layout.height)||card.offsetHeight)+50);});
    page.style.minHeight=`${Math.ceil(bottom)}px`;return true;
  }
  function deviceForWidth(){return innerWidth<=520?'phone':innerWidth<=1050?'tablet':'desktop';}
  let lastRender=null;
  function render(items,{editor=false}={}){document.getElementById('homeFreeformLayer')?.remove();const page=document.querySelector('.page');if(page)page.style.minHeight='';const visible=editor?items:items.filter(x=>x.active!==false);applyHero(visible);renderFeatures(visible);renderCards(visible,'resources','homeResources');renderCards(visible,'dashboard','homeDashboardCards',true);renderCards(visible,'mobile','mobile');renderCards(visible,'documents','documents');renderNavigation(visible);if(editor)document.documentElement.classList.add('homepage-visual-editing');else{lastRender=visible;freeform(visible,deviceForWidth());}}
  window.FP365_HOMEPAGE_RENDER=render;
  window.FP365_HOMEPAGE_FREEFORM=freeform;
  async function load(){if(new URLSearchParams(location.search).has('visualEditor')||!window.supabase)return;const client=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}}),{data,error}=await client.rpc('get_public_homepage',{p_company_code:'WFS'});if(error||!data?.length){if(error)console.warn('Using built-in homepage content.',error.message);return;}render([...data].sort((a,b)=>a.sort_order-b.sort_order));}
  load().catch(error=>console.warn('Using built-in homepage content.',error));
  let resizeTimer;addEventListener('resize',()=>{if(!lastRender)return;clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>render(lastRender),120);});
})();
