(() => {
  'use strict';
  const SUPABASE_URL='https://ahoejwyxfclndcbcxhwv.supabase.co',SUPABASE_KEY='sb_publishable_FeyV-yXT6lwFHh737rYnAQ_mYoP8TIW';
  const byId=id=>document.getElementById(id),itemByKey=(items,key)=>items.find(item=>item.item_key===key);
  const safeUrl=value=>{const url=String(value||'').trim();if(!url)return'';if(/^(#|mailto:|tel:)/i.test(url))return url;try{const parsed=new URL(url,location.href);return['http:','https:'].includes(parsed.protocol)?parsed.href:'';}catch(_){return'';}};
  const applyTextStyle=(element,style={},prefix='')=>{if(!element)return;const size=Number(style[`${prefix}font_size`]),color=style[`${prefix}color`];if(size>=10&&size<=120)element.style.fontSize=`${size}px`;else element.style.removeProperty('font-size');if(/^#[0-9a-f]{6}$/i.test(color||''))element.style.color=color;else element.style.removeProperty('color');};
  const identify=(element,item,field)=>{if(!element||!item)return;element.dataset.homeId=item._draftId||item.id||item.item_key||'';element.dataset.homeField=field;element.hidden=item.style_data?.hidden_fields?.[field]===true;};
  const anchorId=item=>`home-${item.section_key}-${normalized(item.title).replace(/\s+/g,'-')||'card'}`;
  const normalized=value=>String(value||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
  function matchingCard(items,label,source=null){const name=normalized(label),rules=name.includes('admin')?['admin','portal']:name.includes('mobile')?['mobile']:name.includes('fedex')?['fedex']:name.includes('fmcsa')?['fmcsa']:name.includes('weather')?['weather']:name.split(' ').filter(word=>word.length>3),sourceY=Number(source?.style_data?.layouts?.desktop?.y)||-1,candidates=items.filter(item=>item!==source&&item.item_type==='card'&&item.section_key!=='features'&&rules.every(word=>normalized(item.title).includes(word))).sort((a,b)=>{const score=item=>(Number(item.style_data?.layouts?.desktop?.y)>sourceY?100:0)+(name.includes('admin')&&item.section_key==='dashboard'?30:0)+(name.includes('mobile')&&normalized(item.title).includes('overview')?30:0)+(name.includes('fedex')&&normalized(item.title).includes('code')?30:0)+(name.includes('fmcsa')&&item.section_key==='dashboard'?30:0);return score(b)-score(a);});return candidates[0];}
  function inferredUrl(items,item){const requested=String(item.url||'').match(/^#destination-(.+)$/i)?.[1],label=requested||item.title,match=matchingCard(items,label,item);if(match)return`#${anchorId(match)}`;const explicit=safeUrl(item.url);if(explicit&&!requested)return explicit;const name=normalized(label);if(name.includes('weather'))return'#numbers';if(name.includes('admin'))return'#dashboard';if(name.includes('mobile'))return'#mobile';if(name.includes('document'))return'#documents';return'#';}
  function makeLink(item,className='link',fallback=''){const url=safeUrl(item.url)||fallback;if(!url)return null;const link=document.createElement('a');link.className=className;link.href=url;link.textContent=item.link_label||item.title;if(item.open_new_tab&&!url.startsWith('#')){link.target='_blank';link.rel='noopener';}identify(link,item,item.item_type==='link'?'title':'link_label');applyTextStyle(link,item.style_data);return link;}
  function applyHero(items){const eyebrow=itemByKey(items,'hero_eyebrow'),title=itemByKey(items,'hero_title'),accent=itemByKey(items,'hero_accent'),body=itemByKey(items,'hero_body'),button=itemByKey(items,'hero_button');const set=(id,item,field='title')=>{const el=byId(id);if(!el)return;el.hidden=!item;if(!item){delete el.dataset.homeId;delete el.dataset.homeField;return;}el.textContent=item[field]||'';identify(el,item,field);applyTextStyle(el,item.style_data);};set('homeHeroEyebrow',eyebrow);set('homeHeroTitle',title);set('homeHeroSubtitle',title,'body');set('homeHeroAccent',accent);set('homeHeroBody',body);const el=byId('homeHeroButton');if(el){el.hidden=!button;if(!button){delete el.dataset.homeId;delete el.dataset.homeField;}else{const url=safeUrl(button.url);el.textContent=button.title||'';if(url)el.href=url;el.hidden=!url;identify(el,button,'title');applyTextStyle(el,button.style_data);}}}
  function applyHeader(items){const apply=(id,key)=>{const item=itemByKey(items,key),el=byId(id);if(!el)return;el.hidden=!item;if(!item)return;el.textContent=item.title||'';const url=safeUrl(item.url);if(url&&el.tagName==='A')el.href=url;identify(el,item,'title');applyTextStyle(el,item.style_data);};apply('homeBrand','header_brand');apply('homeLogin','header_login');apply('homeHeaderDemo','header_demo');}
  function applyCardStyle(card,item){const style=item.style_data||{},span=Math.max(1,Math.min(5,Number(style.width)||1)),height=Math.max(0,Math.min(800,Number(style.min_height)||0));card.style.setProperty('--home-span',span);if(height)card.style.minHeight=`${height}px`;else card.style.removeProperty('min-height');card.id=anchorId(item);card.dataset.homeId=item._draftId||item.id||'';card.dataset.homeSection=item.section_key;card.dataset.homeActive=item.active===false?'false':'true';}
  function makeIcon(item,className){if(!item.icon)return null;const icon=document.createElement('div');icon.className=className;if(/^https?:\/\//i.test(item.icon)){const image=document.createElement('img');image.src=item.icon;image.alt='';Object.assign(image.style,{display:'block',width:'100%',height:'100%',maxWidth:'96px',maxHeight:'96px',objectFit:'contain'});icon.append(image);}else icon.textContent=item.icon;identify(icon,item,'icon');return icon;}
  function renderFeatures(items){const target=byId('homeFeatures'),rows=items.filter(x=>x.item_type==='card'&&x.section_key==='features');if(!target||!rows.length)return;target.replaceChildren(...rows.map(item=>{const destination=inferredUrl(items,item),row=document.createElement(destination&&destination!=='#'?'a':'div');row.className='feature';if(row.tagName==='A'){row.href=destination;row.setAttribute('aria-label',`Go to ${item.title}`);}applyCardStyle(row,item);const copy=document.createElement('div'),title=document.createElement('b'),body=document.createElement('small');title.textContent=item.title;body.textContent=item.body||'';identify(title,item,'title');identify(body,item,'body');applyTextStyle(title,item.style_data,'title_');applyTextStyle(body,item.style_data,'body_');copy.append(title,body);const icon=makeIcon(item,'icon');if(icon)row.append(icon);row.append(copy);return row;}));target.style.gridTemplateColumns=`repeat(${Math.min(rows.length,5)},minmax(0,1fr))`;}
  function makeCard(item,tile=false,items=[]){const card=document.createElement('article');card.className=tile?'tile':'card';applyCardStyle(card,item);const icon=makeIcon(item,tile?'bigicon':'card-icon');if(icon)card.appendChild(icon);const heading=document.createElement(tile?'h4':'h3');heading.textContent=item.title;identify(heading,item,'title');applyTextStyle(heading,item.style_data,'title_');card.appendChild(heading);if(item.body!=null){const body=document.createElement('p');body.textContent=item.body||'';identify(body,item,'body');applyTextStyle(body,item.style_data,'body_');card.appendChild(body);}const link=makeLink(item,tile?'mini-btn':'link');if(link)card.appendChild(link);const name=normalized(item.title),stripItem=(Number(item.style_data?.layouts?.desktop?.y)||999)>-1&&(Number(item.style_data?.layouts?.desktop?.y)||999)<100&&['admin portal overview','mobile applications','fedex locations','fmcsa'].some(label=>name.includes(label));if(stripItem){const destination=inferredUrl(items,item);if(destination&&destination!=='#'){card.classList.add('home-jump-card');card.tabIndex=0;card.setAttribute('role','link');card.onclick=()=>{if(!document.documentElement.classList.contains('homepage-visual-editing'))location.hash=destination;};card.onkeydown=event=>{if(event.key==='Enter')card.click();};}}return card;}
  function renderCards(items,section,targetId,tile=false){const target=targetId==='documents'?document.querySelector('section.documents-section#documents'):byId(targetId),rows=items.filter(x=>x.item_type==='card'&&x.section_key===section);if(!rows.length||!target)return;const cards=rows.map(x=>makeCard(x,tile,items));if(section==='resources'){target.querySelectorAll('[data-home-section="resources"]').forEach(x=>x.remove());target.append(...cards);}else target.replaceChildren(...cards);}
  function renderNavigation(items){const target=byId('homeNavigation'),rows=items.filter(x=>x.item_type==='link'&&x.section_key==='navigation'&&!String(x.item_key||'').startsWith('header_')),links=rows.map(x=>makeLink(x,'',inferredUrl(items,x))).filter(Boolean);if(!target)return;target.replaceChildren(...links);links[0]?.classList.add('active');}
  function unwrapStaticText(){document.querySelectorAll('[data-home-static-wrapper]').forEach(span=>span.replaceWith(document.createTextNode(span.textContent)));}
  function applyStaticText(items){const state=itemByKey(items,'page_state');if(!state)return;const style=state.style_data||{},content=style.static_content||{},hidden=style.static_hidden||{},root=document.querySelector('.page'),nodes=[];if(!root)return;const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{acceptNode(node){const parent=node.parentElement;if(!node.nodeValue.trim()||!parent||parent.closest('[hidden],[data-home-field],[data-home-section],script,style'))return NodeFilter.FILTER_REJECT;return NodeFilter.FILTER_ACCEPT;}});while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach((node,index)=>{const field=`static__${index}`,span=document.createElement('span');span.dataset.homeStaticWrapper='true';span.textContent=Object.hasOwn(content,field)?content[field]:node.nodeValue;span.hidden=hidden[field]===true;node.replaceWith(span);identify(span,state,field);applyTextStyle(span,style,`${field}_`);});}
  function applyCutoff(items,device){const page=document.querySelector('.page'),state=itemByKey(items,'page_state'),cutoff=Number(state?.style_data?.cutoffs?.[device]),base=Number(state?.style_data?.base_cutoffs?.[device])||cutoff;document.querySelector('.home-cutoff-cover')?.remove();if(!page)return;if(cutoff>0){document.querySelectorAll('[data-home-freeform="true"]').forEach(target=>{const item=items.find(x=>(x._draftId||x.id||x.item_key)===target.dataset.homeId),layout=item&&layoutFor(item,target,device);if(layout&&(Number(layout.y)||0)>=base&&!item.style_data?.keep_below_cutoff)target.hidden=true;});if(cutoff>base){const cover=document.createElement('div');cover.className='home-cutoff-cover';Object.assign(cover.style,{position:'absolute',left:'0',right:'0',top:`${base}px`,height:`${cutoff-base}px`,background:'#05080d',zIndex:'11'});page.append(cover);}page.style.height=`${cutoff}px`;page.style.minHeight=`${cutoff}px`;page.style.overflow='hidden';}else{page.style.removeProperty('height');page.style.removeProperty('overflow');}}
  function layoutFor(item,target,device,create=false){
    item.style_data=item.style_data||{};
    if(target.dataset.homeSection){item.style_data.layouts=item.style_data.layouts||{};if(create&&!item.style_data.layouts[device])item.style_data.layouts[device]={};return item.style_data.layouts[device];}
    const field=target.dataset.homeField||'item';item.style_data.element_layouts=item.style_data.element_layouts||{};item.style_data.element_layouts[device]=item.style_data.element_layouts[device]||{};if(create&&!item.style_data.element_layouts[device][field])item.style_data.element_layouts[device][field]={};return item.style_data.element_layouts[device][field];
  }
  function resetFreeform(){const layer=byId('homeFreeformLayer');if(!layer)return;[...layer.children].forEach(target=>{const placeholder=target._homePlaceholder;if(placeholder?.parentNode)placeholder.replaceWith(target);target._homePlaceholder=null;target.removeAttribute('data-home-freeform');for(const property of ['position','left','top','width','height','min-height','z-index','overflow','box-sizing'])target.style.removeProperty(property);});layer.remove();}
  function freeform(items,device,{initialize=false}={}){
    const page=document.querySelector('.page'),targets=[...document.querySelectorAll('[data-home-section], [data-home-id][data-home-field]')].filter(target=>target.matches('[data-home-section]')||!target.closest('[data-home-section]'));if(!page||!targets.length)return false;
    const pageRect=page.getBoundingClientRect(),flowHeight=Math.max(page.scrollHeight,document.documentElement.scrollHeight),measurements=new Map(targets.map(target=>[target,target.getBoundingClientRect()]));let hasLayout=false;
    targets.forEach((target,index)=>{const item=items.find(x=>(x._draftId||x.id||x.item_key)===target.dataset.homeId);if(!item)return;let layout=layoutFor(item,target,device);if(!layout&&initialize){const rect=measurements.get(target);layout=layoutFor(item,target,device,true);Object.assign(layout,{x:Math.round(rect.left-pageRect.left),y:Math.round(rect.top-pageRect.top),width:Math.round(rect.width),height:Math.round(rect.height),z:index+10});}if(layout&&Number(layout.width)>0)hasLayout=true;});
    if(!hasLayout)return false;let layer=byId('homeFreeformLayer');if(layer)layer.remove();layer=document.createElement('div');layer.id='homeFreeformLayer';layer.className='home-freeform-layer';page.appendChild(layer);let bottom=flowHeight;
    targets.forEach(target=>{const item=items.find(x=>(x._draftId||x.id||x.item_key)===target.dataset.homeId),layout=item&&layoutFor(item,target,device);if(!layout||!Number(layout.width))return;if(target.dataset.homeStaticWrapper){const computed=getComputedStyle(target);for(const property of ['font-family','font-size','font-weight','font-style','line-height','color','letter-spacing','text-transform','text-align'])target.style.setProperty(property,computed.getPropertyValue(property));}const placeholder=document.createComment('homepage-element');target.before(placeholder);target._homePlaceholder=placeholder;target.dataset.homeFreeform='true';target.style.position='absolute';target.style.left=`${Math.max(0,Number(layout.x)||0)}px`;target.style.top=`${Math.max(0,Number(layout.y)||0)}px`;target.style.width=`${Math.max(70,Number(layout.width)||target.offsetWidth)}px`;target.style.height=`${Math.max(38,Number(layout.height)||target.offsetHeight)}px`;target.style.minHeight='0';target.style.zIndex=String(Number(layout.z)||10);target.style.overflow='auto';target.style.boxSizing='border-box';layer.appendChild(target);bottom=Math.max(bottom,(Number(layout.y)||0)+(Number(layout.height)||target.offsetHeight)+50);});
    page.style.minHeight=`${Math.ceil(bottom)}px`;return true;
  }
  function deviceForWidth(){return innerWidth<=520?'phone':innerWidth<=1050?'tablet':'desktop';}
  let lastRender=null;
  function render(items,{editor=false}={}){resetFreeform();unwrapStaticText();const page=document.querySelector('.page');if(page){page.style.minHeight='';page.style.removeProperty('height');page.style.removeProperty('overflow');}const visible=editor?items:items.filter(x=>x.active!==false);applyHeader(visible);applyHero(visible);renderFeatures(visible);renderCards(visible,'resources','homeResources');renderCards(visible,'dashboard','homeDashboardCards',true);renderCards(visible,'mobile','mobile');renderCards(visible,'documents','documents');renderNavigation(visible);applyStaticText(visible);if(editor)document.documentElement.classList.add('homepage-visual-editing');else{lastRender=visible;const device=deviceForWidth();freeform(visible,device);applyCutoff(visible,device);}}
  window.FP365_HOMEPAGE_RENDER=render;
  window.FP365_HOMEPAGE_FREEFORM=freeform;
  window.FP365_HOMEPAGE_LAYOUT_FOR=layoutFor;
  window.FP365_HOMEPAGE_APPLY_CUTOFF=applyCutoff;
  async function load(){if(new URLSearchParams(location.search).has('visualEditor')||!window.supabase)return;const client=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}}),{data,error}=await client.rpc('get_public_homepage',{p_company_code:'WFS'});if(error||!data?.length){if(error)console.warn('Using built-in homepage content.',error.message);return;}render([...data].sort((a,b)=>a.sort_order-b.sort_order));}
  load().catch(error=>console.warn('Using built-in homepage content.',error));
  let resizeTimer;addEventListener('resize',()=>{if(!lastRender)return;clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>render(lastRender),120);});
})();
