(() => {
  "use strict";
  const main=document.querySelector("#main"),title=document.querySelector("#screenTitle"),back=document.querySelector("#backBtn"),menu=document.querySelector("#menuBtn"),modal=document.querySelector("#modal"),modalBody=document.querySelector("#modalBody");
  const demo={driver:"Joe Public",employee:"0001001",truck:"524657",equipment:"53’ Trailer",trailer:"956594",from:"377",to:"8402",photos:new Set(),checklist:new Set(),inspectionComplete:false};
  let screen="welcome",history=[];
  const screens={welcome,home,equipment,details,checklist,photos,review,locations,incident,feedback,eos,complete};
  function go(next,push=true){if(push&&screen!==next)history.push(screen);screen=next;render()}
  function render(){title.textContent=labels[screen]||"Driver Demo";back.disabled=!history.length;main.innerHTML="";screens[screen]();scrollTo({top:0,behavior:"smooth"})}
  const labels={welcome:"Interactive Demo",home:"Driver Home",equipment:"Select Equipment",details:"Inspection Details",checklist:"Pre-Trip Checklist",photos:"Required Photos",review:"Review & Certify",locations:"FedEx Locations",incident:"Accident / Incident",feedback:"Feedback",eos:"End of Shift",complete:"Demo Complete"};
  const card=html=>{const x=document.createElement("section");x.className="card";x.innerHTML=html;main.append(x);return x};
  const bind=(sel,event,fn,root=document)=>root.querySelectorAll(sel).forEach(el=>el.addEventListener(event,fn));
  function welcome(){const c=card(`<div class="hero"><span class="badge">SAFE · SAMPLE DATA ONLY</span><h1>Experience the driver app</h1><p>Take a guided, hands-on tour as <b>Joe Public</b>. Nothing in this demo is sent, stored, emailed, or added to production.</p></div><p class="sample">This interactive demo simulates the real driver workflow without using a live account.</p><button class="primary" data-start>Start Interactive Demo</button>`);bind("[data-start]","click",()=>go("home"),c)}
  function home(){const c=card(`<div class="hero"><span class="badge">SIGNED IN</span><h1>Welcome, ${demo.driver}</h1><p>Employee ID ${demo.employee} · Wade Freight Services</p></div><div class="grid"><button class="choice" data-go="equipment"><strong>Start New Inspection</strong><small>Equipment, checklist, photos and certification</small></button><button class="choice incident" data-go="incident"><strong>Accident / Incident Report</strong><small>Capture location, photos and incident details</small></button><button class="choice" data-go="locations"><strong>FedEx Locations</strong><small>Maps, directions, phone and facility information</small></button><button class="choice" data-go="eos"><strong>End of Shift</strong><small>Review the day and simulate PDF delivery</small></button><button class="choice" data-go="feedback"><strong>Feedback / Suggestion</strong><small>Send a sample app comment</small></button></div>`);bind("[data-go]","click",e=>go(e.currentTarget.dataset.go),c)}
  function equipment(){const c=card(`<h2>Choose equipment type</h2><div class="grid two">${["53’ Trailer","Container","Doubles","Single Pup","Bobtail"].map(x=>`<button class="choice" data-eq="${x}"><strong>${x}</strong><small>Tap to continue</small></button>`).join("")}</div>`);bind("[data-eq]","click",e=>{demo.equipment=e.currentTarget.dataset.eq;go("details")},c)}
  function details(){const c=card(`<div class="steps"><i class="on"></i><i></i><i></i><i></i></div><h2>${demo.equipment}</h2><label>Truck number</label><select id="truck"><option>524657</option><option>524658</option><option>527549</option></select><label>Trailer number</label><div class="row"><input id="trailer" inputmode="numeric" value="${demo.trailer}"><button class="secondary" data-na>NA</button></div><div class="row"><div><label>Location From</label><input id="from" inputmode="numeric" value="${demo.from}"></div><div><label>Location To</label><input id="to" inputmode="numeric" value="${demo.to}"></div></div><label>Notes</label><div class="row"><textarea id="notes" placeholder="Optional inspection notes"></textarea><button class="secondary" data-note-na>NA</button></div><button class="primary" data-next>Continue to Checklist</button>`);bind("[data-na]","click",()=>c.querySelector("#trailer").value="NA",c);bind("[data-note-na]","click",()=>c.querySelector("#notes").value="NA",c);bind("[data-next]","click",()=>{demo.truck=c.querySelector("#truck").value;demo.trailer=c.querySelector("#trailer").value;demo.from=c.querySelector("#from").value;demo.to=c.querySelector("#to").value;go("checklist")},c)}
  function checklist(){const qs=["Walk-around inspection completed","Tires and wheels appear safe","Lights and reflectors checked","Brakes and air system checked","No visible leaks or unsafe defects","Required documents are available"];const c=card(`<div class="steps"><i class="on"></i><i class="on"></i><i></i><i></i></div><h2>Pre-Trip Checklist</h2><p class="muted">Confirm each item to continue.</p>${qs.map((q,i)=>`<label class="check"><input type="checkbox" data-check="${i}" ${demo.checklist.has(i)?"checked":""}><span>${q}</span></label>`).join("")}<button class="primary" data-next disabled>Continue to Photos</button>`);const next=c.querySelector("[data-next]");function sync(){c.querySelectorAll("[data-check]").forEach(x=>x.checked?demo.checklist.add(+x.dataset.check):demo.checklist.delete(+x.dataset.check));next.disabled=demo.checklist.size!==qs.length}bind("[data-check]","change",sync,c);bind("[data-next]","click",()=>go("photos"),c);sync()}
  function photos(){const list=demo.equipment==="Bobtail"?[]:demo.equipment==="Doubles"?["Fifth wheel plate connected to Trailer 1","Trailer 1 rear door and seal secure","Pintle hook and safety chains secure","Fifth wheel plate connected to Trailer 2","Trailer 2 rear door and seal secure"]:["Fifth wheel plate connected","Landing gear raised","Air, brake and electrical lines connected","Rear door and seal secure"];const c=card(`<div class="steps"><i class="on"></i><i class="on"></i><i class="on"></i><i></i></div><h2>Required Photos</h2><p class="muted">Tap Take Demo Photo to simulate each required image.</p>${list.length?list.map((p,i)=>`<div class="photo ${demo.photos.has(i)?"done":""}"><b>${p}</b><div class="photo-preview" ${demo.photos.has(i)?"":"hidden"}>📷 <span>Sample photo captured</span></div><button class="${demo.photos.has(i)?"success":"secondary"}" data-photo="${i}">${demo.photos.has(i)?"✓ Photo Added":"Take Demo Photo"}</button></div>`).join(""):`<div class="sample">Bobtail inspections do not require equipment photos.</div>`}<button class="primary" data-next ${demo.photos.size<list.length?"disabled":""}>Review Inspection</button>`);bind("[data-photo]","click",e=>{demo.photos.add(+e.currentTarget.dataset.photo);photos();main.firstElementChild.remove()},c);bind("[data-next]","click",()=>go("review"),c)}
  function review(){const c=card(`<div class="steps"><i class="on"></i><i class="on"></i><i class="on"></i><i class="on"></i></div><h2>Review Inspection</h2>${summaryRows()}<label class="check"><input id="cert" type="checkbox"><span>I certify this inspection and all sample photographs are complete and accurate.</span></label><button class="primary" data-submit disabled>Submit Demo Inspection</button>`);const cert=c.querySelector("#cert"),submit=c.querySelector("[data-submit]");cert.onchange=()=>submit.disabled=!cert.checked;submit.onclick=()=>{demo.inspectionComplete=true;toast("Demo inspection completed — nothing was sent.");go("home")}}
  function summaryRows(){return [["Driver",demo.driver],["Truck",demo.truck],["Equipment",demo.equipment],["Trailer",demo.trailer],["Route",`${demo.from} → ${demo.to}`],["Photos",`${demo.photos.size} sample photo(s)`]].map(x=>`<div class="summary"><span>${x[0]}</span><b>${x[1]}</b></div>`).join("")}
  function locations(){const c=card(`<h2><span style="color:#4d148c">Fed</span><span style="color:#ff6200">Ex</span> Locations</h2><label>Select a location</label><select id="loc"><option value="377">377 — Murfreesboro Hub</option><option value="406">406 — NOKY</option><option value="8402">8402 — Louisville</option></select><button class="primary" data-show>View Location</button><div id="location"></div>`);bind("[data-show]","click",()=>showLocation(c,c.querySelector("#loc").value),c);showLocation(c,"377")}
  function showLocation(c,code){const data={377:["Murfreesboro Hub","1525 Distribution Drive, Murfreesboro TN","35.792466, -86.369162"],406:["NOKY","11000 Toebben Rd, Independence KY","38.940906, -84.613411"],8402:["Louisville","12900 Plantside Drive, Louisville KY","38.208477, -85.518372"]}[code];c.querySelector("#location").innerHTML=`<div class="map"><span class="map-pin">📍</span><div class="map-controls"><button>+</button><button>−</button></div><button class="locate" data-locate>➤</button></div><h2>${code} ${data[0]}</h2><p>${data[1]}<br><span class="muted">${data[2]}</span></p><div class="grid two"><button class="primary" data-maps>Open in Maps</button><button class="secondary" data-call>Call</button></div><h3>Directions</h3><p class="muted">Follow posted facility signs and dispatcher instructions. This demo shows sample directions only.</p>`;bind("[data-locate]","click",()=>toast("Map centered on this device’s simulated location."),c);bind("[data-maps]","click",()=>toast("Demo: Maps would open here."),c);bind("[data-call]","click",()=>toast("Demo: The phone app would open here."),c)}
  function incident(){const c=card(`<span class="badge" style="border-color:#a33">SIMULATION ONLY</span><h2 style="color:#ff8884">Accident / Incident Report</h2><p class="muted">Location and timestamp captured when this screen opened.</p><div class="summary"><span>Driver</span><b>${demo.driver}</b></div><div class="summary"><span>GPS</span><b>35.846100, -86.391900</b></div><div class="summary"><span>Time</span><b>${new Date().toLocaleString()}</b></div><label>Is the current equipment correct?</label><div class="grid two"><button class="success" data-yes>Yes</button><button class="secondary" data-no>No, update</button></div><div id="incidentForm"></div>`);bind("[data-yes]","click",()=>incidentForm(c,false),c);bind("[data-no]","click",()=>incidentForm(c,true),c)}
  function incidentForm(c,edit){c.querySelector("#incidentForm").innerHTML=`${edit?`<label>Truck / trailer / dolly</label><input value="${demo.truck} / ${demo.trailer} / NA">`:""}<label>Nearest city or town</label><input value="Murfreesboro"><div class="row"><div><label>Mile marker</label><input inputmode="numeric" placeholder="Optional"></div><div><label>Nearest exit</label><input inputmode="numeric" placeholder="Optional"></div></div><label>Highway and direction</label><input placeholder="Example: I-24 West"><label>Details of Incident</label><textarea placeholder="Driver statement and sequence of events"></textarea><label>Photos</label><button class="secondary" data-add-photo>Add Demo Photo</button><label>Injuries or fatalities?</label><select><option>No</option><option>Yes</option></select><label>Hazardous materials involved?</label><select><option>No</option><option>Yes</option></select><label>Fuel spilled?</label><select><option>No</option><option>Yes</option></select><button class="danger" data-report>Generate Demo Accident / Incident PDF</button>`;bind("[data-add-photo]","click",()=>toast("Sample incident photo added."),c);bind("[data-report]","click",()=>{modalBody.innerHTML=`<div class="complete">✓</div><h2>Demo report created</h2><p>In production, the PDF is identified as an Accident / Incident Report, emailed to authorized recipients, and archived in Google Drive.</p><p class="sample">No report or email was created by this demo.</p><button class="primary" data-close>Close</button>`;modal.showModal()},c)}
  function feedback(){const c=card(`<h2>Feedback / Suggestion</h2><label>Subject</label><input value="Interactive demo feedback"><label>Message</label><textarea placeholder="Enter a sample suggestion"></textarea><button class="primary" data-send>Submit Demo Feedback</button>`);bind("[data-send]","click",()=>{toast("Demo feedback accepted — nothing was sent.");go("home")},c)}
  function eos(){const c=card(`<h2>End of Shift</h2><p class="muted">Review the day before completing the shift.</p><div class="summary"><span>Driver</span><b>${demo.driver}</b></div><div class="summary"><span>Completed inspections</span><b>${demo.inspectionComplete?1:0}</b></div><label class="check"><input type="checkbox" data-eos><span>Logged into OFF DUTY in Motive</span></label><label class="check"><input type="checkbox" data-eos><span>Signed logs and left fuel card in truck</span></label><label class="check"><input type="checkbox" data-eos><span>I certify the end-of-shift information</span></label><button class="primary" data-finish disabled>Complete Demo End of Shift</button>`);const btn=c.querySelector("[data-finish]");bind("[data-eos]","change",()=>btn.disabled=[...c.querySelectorAll("[data-eos]")].some(x=>!x.checked),c);bind("[data-finish]","click",()=>go("complete"),c)}
  function complete(){card(`<div class="complete">✓</div><div class="hero"><h1>Demo complete</h1><p>You explored the driver workflow without changing any Fleet Protect 365 records.</p></div><div class="card" style="margin:12px 0 0"><b>In production:</b><p class="muted">The End-of-Shift PDF is emailed to configured recipients and archived in Google Drive.</p></div><button class="primary" data-restart>Restart Interactive Demo</button>`);bind("[data-restart]","click",restart)}
  function openMenu(){modalBody.innerHTML=`<h2>Driver Menu</h2><button class="menu-link" data-nav="locations">FedEx Locations</button><button class="menu-link" data-info="fmcsa">FMCSA Resources</button><button class="menu-link" data-info="links">Important Links</button><button class="menu-link" data-nav="feedback">Feedback / Suggestion</button><button class="menu-link" data-restart>Restart Demo</button>`;modal.showModal()}
  function toast(msg){document.querySelector(".toast")?.remove();const el=document.createElement("div");el.className="toast";el.textContent=msg;document.body.append(el);setTimeout(()=>el.remove(),2800)}
  function restart(){history=[];screen="welcome";demo.photos.clear();demo.checklist.clear();demo.inspectionComplete=false;modal.close();render()}
  back.onclick=()=>{if(history.length){screen=history.pop();render()}};menu.onclick=openMenu;document.querySelector("#homeBtn").onclick=()=>go("home");document.querySelector("#restartTop").onclick=restart;document.addEventListener("click",e=>{if(e.target.matches("[data-close]"))modal.close();if(e.target.matches("[data-nav]")){modal.close();go(e.target.dataset.nav)}if(e.target.matches("[data-restart]"))restart();if(e.target.matches('[data-info="fmcsa"]')){modalBody.innerHTML=`<button class="modal-x" data-close>×</button><h2>FMCSA Resources</h2><button class="menu-link">Hours of Service</button><button class="menu-link">Safety Regulations</button><p class="sample">Demo links do not leave this page.</p>`}if(e.target.matches('[data-info="links"]')){modalBody.innerHTML=`<button class="modal-x" data-close>×</button><h2>Important Links</h2><button class="menu-link">Wade Freight Driver Resources</button><button class="menu-link">Safety & Emergency Contacts</button><p class="sample">Demo links do not leave this page.</p>`}});render();
})();
