(() => {
  "use strict";
  const $ = id => document.getElementById(id);
  const esc = value => String(value ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
  const KEY = "fp365_fedex_locations_test_v2";
  const sample = Array.isArray(window.FP365_FEDEX_TEST_SEED) ? window.FP365_FEDEX_TEST_SEED : [];
  let locations = load(), figures = [], links = [];
  function load(){try{const value=JSON.parse(localStorage.getItem(KEY)||"null");return Array.isArray(value)?value:sample}catch{return sample}}
  function save(){localStorage.setItem(KEY,JSON.stringify(locations))}
  function phone(value){const d=String(value||"").replace(/\D/g,"").slice(0,10);return d.length===10?`(${d.slice(0,3)})-${d.slice(3,6)}-${d.slice(6)}`:d}
  function mode(driver){$("adminView").hidden=driver;$("driverView").hidden=!driver;$("adminMode").classList.toggle("active",!driver);$("driverMode").classList.toggle("active",driver);if(driver)renderDriverOptions();else renderAdmin()}
  $("adminMode").onclick=()=>mode(false);$("driverMode").onclick=()=>mode(true);
  function renderAdmin(){const q=$("searchAdmin").value.trim().toLowerCase();const rows=locations.filter(x=>!q||x.code.includes(q)||x.name.toLowerCase().includes(q));$("locationRows").innerHTML=rows.map(x=>`<tr><td>${esc(x.code)}</td><td><strong>${esc(x.name)}</strong></td><td>${esc(x.address||"—")}</td><td>${x.latitude||"—"}, ${x.longitude||"—"}</td><td><div class="row-actions"><button data-view="${x.id}">View</button><button data-edit="${x.id}">Edit</button><button class="danger" data-delete="${x.id}">Delete</button></div></td></tr>`).join("")||'<tr><td colspan="5">No locations found.</td></tr>';document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>{mode(true);showLocation(b.dataset.view)});document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>openEditor(locations.find(x=>x.id===b.dataset.edit)));document.querySelectorAll("[data-delete]").forEach(b=>b.onclick=()=>{if(confirm("Delete this test location?")){locations=locations.filter(x=>x.id!==b.dataset.delete);save();renderAdmin()}})}
  $("searchAdmin").oninput=renderAdmin;$("addBtn").onclick=()=>openEditor();
  const routeLabels=["Primary Route","Secondary Route (Optional)","Third Route (Optional)"];
  function routeEditor(routes=[]){$("routes").innerHTML=routeLabels.map((title,i)=>`<section class="route-editor"><h3>${title}</h3><div class="grid"><label>From Code${i?` ${i+1}`:""}<input class="route-from" inputmode="numeric" maxlength="10" value="${esc(routes[i]?.from||"")}"></label><label>To Code${i?` ${i+1}`:""}<input class="route-to" inputmode="numeric" maxlength="10" value="${esc(routes[i]?.to||"")}"></label></div><label>Directions to Next Location (750 chars)<textarea class="route-directions" maxlength="750">${esc(routes[i]?.directions||"")}</textarea></label></section>`).join("")}
  function openEditor(item){$("locationForm").reset();$("recordId").value=item?.id||"";$("dialogTitle").textContent=item?"Edit Location":"Create Location";[["code","code"],["name","name"],["locationAddress","address"],["latitude","latitude"],["longitude","longitude"],["phone","phone"],["generalDirections","directions"],["locationInstructions","instructions"],["locationNotes","notes"]].forEach(([id,key])=>$(id).value=item?.[key]??"");figures=[...(item?.figures||[])];links=[...(item?.links||[])];routeEditor(item?.routes);renderFigures();renderLinks();selectTab("basic");$("formMsg").textContent="";$("editor").showModal()}
  function selectTab(name){document.querySelectorAll("[data-tab]").forEach(x=>x.classList.toggle("active",x.dataset.tab===name));document.querySelectorAll("[data-panel]").forEach(x=>x.classList.toggle("active",x.dataset.panel===name))}
  document.querySelectorAll("[data-tab]").forEach(x=>x.onclick=()=>selectTab(x.dataset.tab));$("closeEditor").onclick=$("cancelEditor").onclick=()=>$("editor").close();
  $("phone").oninput=e=>e.target.value=phone(e.target.value);
  document.addEventListener("input",e=>{if(e.target.matches('[inputmode="numeric"]'))e.target.value=e.target.value.replace(/\D/g,"").slice(0,10)});
  $("locationForm").onsubmit=e=>{e.preventDefault();const code=$("code").value.trim();if(locations.some(x=>x.code===code&&x.id!==$("recordId").value)){return $("formMsg").textContent="Unique Code is already in use."}const from=[...document.querySelectorAll(".route-from")],to=[...document.querySelectorAll(".route-to")],directions=[...document.querySelectorAll(".route-directions")];const record={id:$("recordId").value||crypto.randomUUID(),code,name:$("name").value.trim(),address:$("locationAddress").value.trim(),latitude:Number($("latitude").value)||null,longitude:Number($("longitude").value)||null,phone:phone($("phone").value),routes:routeLabels.map((_,i)=>({from:from[i].value,to:to[i].value,directions:directions[i].value.trim()})),directions:$("generalDirections").value.trim(),instructions:$("locationInstructions").value.trim(),notes:$("locationNotes").value.trim(),figures,links};const at=locations.findIndex(x=>x.id===record.id);if(at>=0)locations[at]=record;else locations.push(record);save();$("editor").close();renderAdmin()};
  $("figureInput").onchange=async e=>{for(const file of [...e.target.files].slice(0,5-figures.length)){if(file.size>2.5*1024*1024){$("formMsg").textContent="Each test figure must be 2.5 MB or smaller.";continue}figures.push({name:file.name,data:await dataUrl(file)})}e.target.value="";renderFigures()};
  function dataUrl(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}
  function renderFigures(){$("figureEditor").innerHTML=figures.map((x,i)=>`<div class="figure"><img src="${x.data}" alt="${esc(x.name)}" data-photo="${i}"><button type="button" data-remove-photo="${i}">×</button></div>`).join("");document.querySelectorAll("[data-remove-photo]").forEach(b=>b.onclick=()=>{figures.splice(Number(b.dataset.removePhoto),1);renderFigures()});document.querySelectorAll("[data-photo]").forEach(img=>img.onclick=()=>viewPhoto(img.src));$("figureHint").textContent=`${figures.length} of 5 photos added.`}
  $("addLink").onclick=()=>{if(links.length<5){links.push({title:"",url:""});renderLinks()}};
  function renderLinks(){$("linkEditor").innerHTML=links.map((x,i)=>`<div class="link-row"><input class="link-title" value="${esc(x.title)}" placeholder="Link title"><input class="link-url" type="url" value="${esc(x.url)}" placeholder="https://..."><button type="button" data-remove-link="${i}">×</button></div>`).join("");document.querySelectorAll(".link-title,.link-url").forEach((x,i)=>x.oninput=()=>{const at=Math.floor(i/2);links[at][x.classList.contains("link-title")?"title":"url"]=x.value});document.querySelectorAll("[data-remove-link]").forEach(b=>b.onclick=()=>{links.splice(Number(b.dataset.removeLink),1);renderLinks()})}
  function renderDriverOptions(){$("locationSelect").innerHTML='<option value="">Select a location</option>'+[...locations].sort((a,b)=>a.name.localeCompare(b.name)).map(x=>`<option value="${x.id}">${esc(x.name)} (${esc(x.code)})</option>`).join("")}
  $("locationSelect").onchange=e=>e.target.value&&showLocation(e.target.value);$("lookupBtn").onclick=()=>{const item=locations.find(x=>x.code===$("codeLookup").value.trim());if(item)showLocation(item.id);else alert("Location code not found in test data.")};$("homeBtn").onclick=()=>{$("locationCard").hidden=true;$("driverEmpty").hidden=false;$("locationSelect").value="";$("codeLookup").value=""};
  function showLocation(id){const x=locations.find(v=>v.id===id);if(!x)return;$("driverEmpty").hidden=true;$("locationCard").hidden=false;$("locationSelect").value=x.id;$("driverName").textContent=`${x.code} ${x.name}`;$("coords").textContent=x.latitude&&x.longitude?`${x.latitude}, ${x.longitude}`:"Coordinates unavailable";$("address").textContent=x.address||"Address unavailable";const maps=x.latitude&&x.longitude?`https://www.google.com/maps/search/?api=1&query=${x.latitude},${x.longitude}`:`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(x.address)}`;$("mapsBtn").href=maps;$("map").src=x.latitude&&x.longitude?`https://www.google.com/maps?q=${x.latitude},${x.longitude}&z=15&output=embed`:"about:blank";$("callBtn").hidden=!x.phone;$("callBtn").href=`tel:${String(x.phone||"").replace(/\D/g,"")}`;$("routeCards").innerHTML=(x.routes||[]).filter(r=>r.from&&r.to).map((r,i)=>`<details class="route-card"><summary><span>FROM${i?` (${i+1})`:""}: ${esc(r.from)}</span><span>TO${i?` (${i+1})`:""}: ${esc(r.to)}</span></summary><p>${esc(r.directions||"No directions added.")}</p></details>`).join("");$("directions").textContent=x.directions||"No general directions added.";$("instructions").textContent=x.instructions||"No instructions added.";$("notes").textContent=x.notes||"No notes added.";$("driverFigures").innerHTML=(x.figures||[]).map((f,i)=>`<div class="figure"><img src="${f.data}" alt="${esc(f.name)}" data-driver-photo="${i}"></div>`).join("")||"No reference figures added.";document.querySelectorAll("[data-driver-photo]").forEach(img=>img.onclick=()=>viewPhoto(img.src));$("driverLinks").innerHTML=(x.links||[]).filter(l=>l.url).map(l=>`<a href="${esc(l.url)}" target="_blank" rel="noopener">${esc(l.title||l.url)}</a>`).join("")||"No external links added.";window.scrollTo({top:0,behavior:"smooth"})}
  function viewPhoto(src){$("fullPhoto").src=src;$("photoViewer").showModal()}$("closePhoto").onclick=()=>$("photoViewer").close();
  $("exportBtn").onclick=()=>{const headers=["code","name","address","latitude","longitude","phone","routes","directions","instructions","notes","links"];const csv=[headers.join(","),...locations.map(x=>headers.map(h=>csvCell(typeof x[h]==="object"?JSON.stringify(x[h]):x[h])).join(","))].join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="fedex-locations-test.csv";a.click();URL.revokeObjectURL(a.href)};
  function csvCell(v){return `"${String(v??"").replaceAll('"','""')}"`}
  $("importBtn").onclick=()=>$("csvFile").click();$("csvFile").onchange=async e=>{const text=await e.target.files[0].text();const rows=parseCsv(text),headers=rows.shift()||[];for(const row of rows){const o=Object.fromEntries(headers.map((h,i)=>[h,row[i]||""]));if(!o.code||!o.name)continue;const existing=locations.find(x=>x.code===o.code);const record={...(existing||{}),id:existing?.id||crypto.randomUUID(),code:o.code.replace(/\D/g,"").slice(0,10),name:o.name,address:o.address||"",latitude:Number(o.latitude)||null,longitude:Number(o.longitude)||null,phone:phone(o.phone),routes:safeJson(o.routes,[]),directions:o.directions||"",instructions:o.instructions||"",notes:o.notes||"",links:safeJson(o.links,[]),figures:existing?.figures||[]};if(existing)Object.assign(existing,record);else locations.push(record)}save();renderAdmin();e.target.value=""};
  function safeJson(v,f){try{return JSON.parse(v)}catch{return f}}function parseCsv(text){const rows=[];let row=[],cell="",quote=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&quote&&n==='"'){cell+='"';i++}else if(c==='"')quote=!quote;else if(c===","&&!quote){row.push(cell);cell=""}else if((c==="\n"||c==="\r")&&!quote){if(c==="\r"&&n==="\n")i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell=""}else cell+=c}row.push(cell);if(row.some(Boolean))rows.push(row);return rows}
  renderAdmin();
})();
