(() => {
  'use strict';
  const s=window.FP365_ADMIN_CLIENT;if(!s)return;
  const $=id=>document.getElementById(id),sections=['features','resources','dashboard','mobile','documents','navigation'];
  let profile,company,items=[],versions=[],frameReady=false,selectedNode=null,selectedItem=null,dirty=false,currentDevice='desktop';
  const newId=()=>crypto.randomUUID?crypto.randomUUID():`draft-${Date.now()}-${Math.random()}`;
  const findItem=id=>items.find(x=>(x._draftId||x.id||x.item_key)===id);
  async function context(){if(profile&&company)return;const {data:session}=await s.auth.getSession(),user=session.session?.user;if(!user)throw new Error('Admin session is unavailable.');const {data,error}=await s.from('employee_profiles').select('*,companies(*)').eq('id',user.id).single();if(error)throw error;profile=data;company=Array.isArray(data.companies)?data.companies[0]:data.companies;if(!company?.id)throw new Error('Company record not found.');}
  function normalize(){for(const section of sections){items.filter(x=>x.item_type!=='text'&&x.section_key===section).sort((a,b)=>a.sort_order-b.sort_order).forEach((x,i)=>x.sort_order=(i+1)*10);}}
  function markDirty(message='Draft changed. Publish when ready.'){dirty=true;$('homepageMsg').textContent=message;}
  function styleKey(item,field,kind){if(item.item_type==='card'&&field==='title')return`title_${kind}`;if(item.item_type==='card'&&field==='body')return`body_${kind}`;return kind;}
  function selectNode(node){
    const card=node?.closest?.('[data-home-section]'),id=node?.dataset.homeId||card?.dataset.homeId,item=findItem(id);if(!item)return;
    selectedNode=node;selectedItem=item;const toolbar=$('homepageTextToolbar');toolbar.classList.remove('hidden');
    const field=node.dataset.homeField||'',textSelected=!!field,keySize=styleKey(item,field,'font_size'),keyColor=styleKey(item,field,'color'),computed=node.ownerDocument.defaultView.getComputedStyle(node);
    $('homepageSelectionLabel').textContent=textSelected?`Editing ${field.replace('_',' ')}`:`Selected ${item.title||'card'}`;
    $('homepageFontSize').disabled=!textSelected;$('homepageFontColor').disabled=!textSelected;$('homepageResetStyle').disabled=!textSelected;
    $('homepageFontSize').value=item.style_data?.[keySize]||Math.round(parseFloat(computed.fontSize)||16);
    $('homepageFontColor').value=item.style_data?.[keyColor]||rgbToHex(computed.color)||'#ffffff';
    const movable=!!node.dataset.homeFreeform;$('homepageEditLink').classList.toggle('hidden',!('url'in item));$('homepageBringFront').classList.toggle('hidden',!movable);$('homepageSendBack').classList.toggle('hidden',!movable);$('homepageHideItem').classList.toggle('hidden',item.item_type==='text');$('homepageDeleteItem').classList.toggle('hidden',item.item_type==='text');
    $('homepageHideItem').textContent=item.active===false?'Show':'Hide';
    node.ownerDocument.querySelectorAll('.home-selected').forEach(x=>x.classList.remove('home-selected'));(textSelected?node:card)?.classList.add('home-selected');
  }
  function rgbToHex(value){const m=String(value).match(/\d+/g);return m&&m.length>=3?'#'+m.slice(0,3).map(x=>(+x).toString(16).padStart(2,'0')).join(''):'';}
  function renderCanvas(keepScroll=true){
    const frame=$('homepageCanvas'),win=frame.contentWindow,doc=frame.contentDocument;if(!frameReady||!win?.FP365_HOMEPAGE_RENDER||!doc)return;
    const y=keepScroll?win.scrollY:0;selectedNode=selectedItem=null;$('homepageTextToolbar').classList.add('hidden');win.FP365_HOMEPAGE_RENDER([...items].sort((a,b)=>a.sort_order-b.sort_order),{editor:true});win.FP365_HOMEPAGE_FREEFORM?.(items,currentDevice,{initialize:true});
    doc.querySelectorAll('[data-home-id][data-home-field]').forEach(node=>{node.contentEditable='plaintext-only';node.spellcheck=true;node.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();selectNode(node);});node.addEventListener('input',()=>{const item=findItem(node.dataset.homeId);if(!item)return;const copy=node.cloneNode(true);copy.querySelectorAll('.home-drag-handle,.home-resize-handle').forEach(x=>x.remove());item[node.dataset.homeField]=copy.innerText.trim();markDirty();});node.addEventListener('keydown',event=>{if(node.tagName==='A'&&event.key==='Enter')event.preventDefault();});});
    doc.querySelectorAll('[data-home-section], [data-home-freeform="true"]').forEach(target=>decorateTarget(target));doc.addEventListener('click',event=>{if(!event.target.closest('[data-home-id]')){doc.querySelectorAll('.home-selected').forEach(x=>x.classList.remove('home-selected'));$('homepageTextToolbar').classList.add('hidden');}});win.scrollTo(0,y);
  }
  function decorateTarget(target){
    const doc=target.ownerDocument,move=doc.createElement('span');move.className='home-drag-handle';move.contentEditable='false';move.textContent='MOVE';target.append(move);for(const edge of ['n','ne','e','se','s','sw','w','nw']){const handle=doc.createElement('span');handle.className='home-resize-handle';handle.contentEditable='false';handle.dataset.edge=edge;handle.title=`Resize ${edge}`;handle.addEventListener('pointerdown',event=>startResize(event,target,edge));target.append(handle);}
    target.addEventListener('click',event=>{if(event.target.closest('.home-drag-handle,.home-resize-handle'))return;event.stopPropagation();selectNode(target);});move.addEventListener('pointerdown',event=>startMove(event,target));
  }
  function targetLayout(target){const item=findItem(target.dataset.homeId);return item&&target.ownerDocument.defaultView.FP365_HOMEPAGE_LAYOUT_FOR?.(item,target,currentDevice);}
  function allLevels(){return [...$('homepageCanvas').contentDocument.querySelectorAll('[data-home-freeform="true"]')].map(x=>Number(targetLayout(x)?.z)||10);}
  function startMove(event,target){
    event.preventDefault();event.stopPropagation();const doc=target.ownerDocument,layout=targetLayout(target);if(!layout)return;const startX=event.clientX,startY=event.clientY,startLeft=Number(layout.x)||0,startTop=Number(layout.y)||0;target.classList.add('home-dragging');target.style.zIndex=String(Math.max(...allLevels(),10)+1);layout.z=Number(target.style.zIndex);event.target.setPointerCapture?.(event.pointerId);
    const move=e=>{layout.x=Math.max(0,Math.round(startLeft+e.clientX-startX));layout.y=Math.max(0,Math.round(startTop+e.clientY-startY));target.style.left=`${layout.x}px`;target.style.top=`${layout.y}px`;};
    const end=()=>{target.classList.remove('home-dragging');doc.removeEventListener('pointermove',move);doc.removeEventListener('pointerup',end);markDirty('Element moved. Publish when ready.');selectNode(target);};
    doc.addEventListener('pointermove',move);doc.addEventListener('pointerup',end,{once:true});
  }
  function startResize(event,target,edge){
    event.preventDefault();event.stopPropagation();const doc=target.ownerDocument,layout=targetLayout(target);if(!layout)return;const startX=event.clientX,startY=event.clientY,start={x:Number(layout.x)||0,y:Number(layout.y)||0,width:Number(layout.width)||target.offsetWidth,height:Number(layout.height)||target.offsetHeight};event.target.setPointerCapture?.(event.pointerId);
    const move=e=>{const dx=e.clientX-startX,dy=e.clientY-startY;let{x,y,width,height}=start;if(edge.includes('e'))width=Math.max(70,start.width+dx);if(edge.includes('s'))height=Math.max(38,start.height+dy);if(edge.includes('w')){width=Math.max(70,start.width-dx);x=start.x+(start.width-width);}if(edge.includes('n')){height=Math.max(38,start.height-dy);y=start.y+(start.height-height);}Object.assign(layout,{x:Math.max(0,Math.round(x)),y:Math.max(0,Math.round(y)),width:Math.round(width),height:Math.round(height)});Object.assign(target.style,{left:`${layout.x}px`,top:`${layout.y}px`,width:`${layout.width}px`,height:`${layout.height}px`});};
    const end=()=>{doc.removeEventListener('pointermove',move);doc.removeEventListener('pointerup',end);markDirty('Element resized. Publish when ready.');selectNode(target);};doc.addEventListener('pointermove',move);doc.addEventListener('pointerup',end,{once:true});
  }
  function applyStyle(kind,value){if(!selectedItem||!selectedNode?.dataset.homeField)return;const field=selectedNode.dataset.homeField,key=styleKey(selectedItem,field,kind);selectedItem.style_data={...(selectedItem.style_data||{})};if(value)selectedItem.style_data[key]=value;else delete selectedItem.style_data[key];if(kind==='font_size')selectedNode.style.fontSize=value?`${value}px`:'';else selectedNode.style.color=value||'';markDirty();}
  function deriveDeviceLayout(device){
    if(device==='desktop'||items.some(x=>x.style_data?.layouts?.[device]))return;const cards=items.filter(x=>x.item_type==='card'&&x.active!==false),source=cards.map(item=>({item,layout:item.style_data?.layouts?.desktop})).filter(x=>x.layout).sort((a,b)=>a.layout.y-b.layout.y||a.layout.x-b.layout.x);if(!source.length)return;const targetWidth=$('homepageCanvas').clientWidth||400,margin=12,gap=12;
    if(device==='phone'){let y=580;source.forEach(({item,layout})=>{const width=Math.max(180,targetWidth-margin*2),height=Math.max(90,Math.min(420,Number(layout.height)||140));item.style_data.layouts[device]={x:margin,y,width,height,z:Number(layout.z)||10};y+=height+gap;});}
    else{const columns=2,width=Math.max(220,(targetWidth-margin*2-gap)/columns);let y=520,rowHeight=0;source.forEach(({item,layout},index)=>{const column=index%columns,height=Math.max(90,Math.min(440,Number(layout.height)||150));if(column===0&&index)y+=rowHeight+gap;item.style_data.layouts[device]={x:margin+column*(width+gap),y,width,height,z:Number(layout.z)||10};rowHeight=Math.max(rowHeight,height);});}
    markDirty(`${device==='phone'?'Phone':'Tablet'} layout generated from the computer layout. You can fine-tune it independently.`);
  }
  function changeLayer(direction){if(!selectedNode)return;const layout=targetLayout(selectedNode),levels=allLevels();if(!layout)return;layout.z=direction==='front'?Math.max(...levels,10)+1:Math.min(...levels,10)-1;markDirty(direction==='front'?'Element brought to front.':'Element sent backward.');renderCanvas();}
  function openEditor(){
    $('homepageItemDialogTitle').textContent='Add to Homepage';$('homepageItemId').value=newId();$('homepageItemType').value='card';$('homepageItemSection').value='dashboard';$('homepageItemTitle').value='';$('homepageItemBody').value='';$('homepageItemIcon').value='';$('homepageItemUrl').value='';$('homepageItemLinkLabel').value='';$('homepageItemNewTab').checked=false;$('homepageItemMsg').textContent='';updateDialogFields();$('homepageItemDialog').showModal();
  }
  function updateDialogFields(){const link=$('homepageItemType').value==='link';$('homepageItemSection').value=link?'navigation':($('homepageItemSection').value==='navigation'?'dashboard':$('homepageItemSection').value);$('homepageItemSection').disabled=link;$('homepageItemBodyRow').classList.toggle('hidden',link);$('homepageItemIconRow').classList.toggle('hidden',link);$('homepageItemLinkLabelRow').classList.toggle('hidden',link);}
  function addItem(event){event.preventDefault();const title=$('homepageItemTitle').value.trim();if(!title){$('homepageItemMsg').textContent='Enter a title.';return;}const type=$('homepageItemType').value,section=type==='link'?'navigation':$('homepageItemSection').value;items.push({_draftId:$('homepageItemId').value,item_type:type,section_key:section,item_key:null,title,body:$('homepageItemBody').value.trim(),url:$('homepageItemUrl').value.trim(),icon:$('homepageItemIcon').value.trim(),link_label:$('homepageItemLinkLabel').value.trim(),sort_order:999,active:true,open_new_tab:$('homepageItemNewTab').checked,style_data:{}});normalize();$('homepageItemDialog').close();markDirty('Item added. Publish when ready.');renderCanvas();}
  async function publish(){try{normalize();$('homepageMsg').textContent='Publishing homepage…';$('publishHomepage').disabled=true;const payload=items.map(({_draftId,id,company_id,created_at,updated_at,created_by,updated_by,...item})=>item),{error}=await s.rpc('publish_homepage_content',{p_items:payload});if(error)throw error;dirty=false;await load();$('homepageMsg').textContent='Published. The live homepage now matches this canvas.';}catch(error){$('homepageMsg').textContent=error.message;}finally{$('publishHomepage').disabled=false;}}
  async function restore(){const id=$('homepageVersion').value;if(!id)return;$('homepageMsg').textContent='Restoring version…';const {error}=await s.rpc('restore_homepage_version',{p_version_id:id});if(error){$('homepageMsg').textContent=error.message;return;}await load();$('homepageMsg').textContent='Previous version restored and published.';}
  async function load(){try{await context();$('homepageMsg').textContent='Loading the live homepage canvas…';const [content,history]=await Promise.all([s.from('homepage_content').select('*').eq('company_id',company.id).order('section_key').order('sort_order'),s.from('homepage_versions').select('id,created_at').eq('company_id',company.id).order('created_at',{ascending:false}).limit(20)]);if(content.error)throw content.error;if(history.error)throw history.error;items=(content.data||[]).map(x=>({...x,style_data:x.style_data||{},_draftId:x.id||newId()}));versions=history.data||[];$('homepageVersion').innerHTML='<option value="">Choose a previous version</option>'+versions.map(x=>`<option value="${x.id}">${new Date(x.created_at).toLocaleString()}</option>`).join('');dirty=false;$('homepageMsg').textContent='Click directly on text or use the purple controls on a card.';renderCanvas(false);}catch(error){$('homepageMsg').textContent=error.message;}}
  function frameLoaded(){frameReady=true;renderCanvas(false);setTimeout(()=>renderCanvas(false),400);}
  function show(){document.querySelectorAll('.view').forEach(x=>x.classList.add('hidden'));$('homepage').classList.remove('hidden');document.querySelectorAll('nav [data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view==='homepage'));$('title').textContent='Visual Homepage Editor';load();}
  document.querySelector('nav [data-view="homepage"]')?.addEventListener('click',show);$('homepageCanvas').addEventListener('load',frameLoaded);$('addHomepageCard').onclick=openEditor;$('publishHomepage').onclick=publish;$('restoreHomepage').onclick=restore;$('homepageItemType').onchange=updateDialogFields;$('homepageItemForm').onsubmit=addItem;$('cancelHomepageItem').onclick=()=>$('homepageItemDialog').close();
  document.querySelectorAll('[data-canvas-size]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-canvas-size]').forEach(x=>x.classList.toggle('active',x===button));currentDevice=button.dataset.canvasSize;$('homepageCanvasShell').className=`homepage-canvas-shell ${currentDevice}`;setTimeout(()=>{deriveDeviceLayout(currentDevice);renderCanvas(false);},230);});
  $('homepageFontSize').oninput=event=>applyStyle('font_size',Math.max(10,Math.min(120,Number(event.target.value)||16)));$('homepageFontColor').oninput=event=>applyStyle('color',event.target.value);$('homepageResetStyle').onclick=()=>{applyStyle('font_size',null);applyStyle('color',null);selectNode(selectedNode);};
  $('homepageEditLink').onclick=()=>{if(!selectedItem)return;const next=prompt('Link address',selectedItem.url||'');if(next===null)return;selectedItem.url=next.trim();markDirty('Link changed. Publish when ready.');renderCanvas();};
  $('homepageBringFront').onclick=()=>changeLayer('front');$('homepageSendBack').onclick=()=>changeLayer('back');
  $('homepageHideItem').onclick=()=>{if(!selectedItem)return;selectedItem.active=selectedItem.active===false;markDirty(selectedItem.active?'Item will be shown.':'Item will be hidden.');renderCanvas();};
  $('homepageDeleteItem').onclick=()=>{if(!selectedItem||!confirm(`Delete “${selectedItem.title||'this item'}” from the draft?`))return;items=items.filter(x=>x!==selectedItem);normalize();markDirty('Item deleted from the draft. Publish when ready.');renderCanvas();};
  window.addEventListener('beforeunload',event=>{if(!dirty)return;event.preventDefault();event.returnValue='';});
})();
