(() => {
  'use strict';
  const s=window.FP365_ADMIN_CLIENT;if(!s)return;
  const $=id=>document.getElementById(id),sections=['features','resources','dashboard','mobile','documents','navigation'];
  let profile,company,items=[],versions=[],frameReady=false,selectedNode=null,selectedItem=null,dirty=false;
  const newId=()=>crypto.randomUUID?crypto.randomUUID():`draft-${Date.now()}-${Math.random()}`;
  const findItem=id=>items.find(x=>(x._draftId||x.id||x.item_key)===id);
  async function context(){if(profile&&company)return;const {data:session}=await s.auth.getSession(),user=session.session?.user;if(!user)throw new Error('Admin session is unavailable.');const {data,error}=await s.from('employee_profiles').select('*,companies(*)').eq('id',user.id).single();if(error)throw error;profile=data;company=Array.isArray(data.companies)?data.companies[0]:data.companies;if(!company?.id)throw new Error('Company record not found.');}
  function normalize(){for(const section of sections){items.filter(x=>x.item_type!=='text'&&x.section_key===section).sort((a,b)=>a.sort_order-b.sort_order).forEach((x,i)=>x.sort_order=(i+1)*10);}}
  function markDirty(message='Draft changed. Publish when ready.'){dirty=true;$('homepageMsg').textContent=message;}
  function styleKey(item,field,kind){if(item.item_type==='card'&&field==='title')return`title_${kind}`;if(item.item_type==='card'&&field==='body')return`body_${kind}`;return kind;}
  function selectNode(node){
    const card=node?.closest?.('[data-home-section]'),id=node?.dataset.homeId||card?.dataset.homeId,item=findItem(id);if(!item)return;
    selectedNode=node;selectedItem=item;const toolbar=$('homepageTextToolbar');toolbar.classList.remove('hidden');
    const field=node.dataset.homeField||'',textSelected=!!field,keySize=styleKey(item,field,'font_size'),keyColor=styleKey(item,field,'color'),computed=node.ownerDocument.defaultView.getComputedStyle(node);
    $('homepageSelectionLabel').textContent=textSelected?`Editing ${field.replace('_',' ')}`:`Selected ${item.title||'card'}`;
    $('homepageFontSize').disabled=!textSelected;$('homepageFontColor').disabled=!textSelected;$('homepageResetStyle').disabled=!textSelected;
    $('homepageFontSize').value=item.style_data?.[keySize]||Math.round(parseFloat(computed.fontSize)||16);
    $('homepageFontColor').value=item.style_data?.[keyColor]||rgbToHex(computed.color)||'#ffffff';
    $('homepageEditLink').classList.toggle('hidden',!('url'in item));$('homepageHideItem').classList.toggle('hidden',item.item_type==='text');$('homepageDeleteItem').classList.toggle('hidden',item.item_type==='text');
    $('homepageHideItem').textContent=item.active===false?'Show':'Hide';
    node.ownerDocument.querySelectorAll('.home-selected').forEach(x=>x.classList.remove('home-selected'));(textSelected?node:card)?.classList.add('home-selected');
  }
  function rgbToHex(value){const m=String(value).match(/\d+/g);return m&&m.length>=3?'#'+m.slice(0,3).map(x=>(+x).toString(16).padStart(2,'0')).join(''):'';}
  function renderCanvas(keepScroll=true){
    const frame=$('homepageCanvas'),win=frame.contentWindow,doc=frame.contentDocument;if(!frameReady||!win?.FP365_HOMEPAGE_RENDER||!doc)return;
    const y=keepScroll?win.scrollY:0;selectedNode=selectedItem=null;$('homepageTextToolbar').classList.add('hidden');win.FP365_HOMEPAGE_RENDER([...items].sort((a,b)=>a.sort_order-b.sort_order),{editor:true});
    doc.querySelectorAll('[data-home-id][data-home-field]').forEach(node=>{node.contentEditable='plaintext-only';node.spellcheck=true;node.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();selectNode(node);});node.addEventListener('input',()=>{const item=findItem(node.dataset.homeId);if(!item)return;item[node.dataset.homeField]=node.innerText.trim();markDirty();});node.addEventListener('keydown',event=>{if(node.tagName==='A'&&event.key==='Enter')event.preventDefault();});});
    doc.querySelectorAll('[data-home-section]').forEach(card=>decorateCard(card));doc.addEventListener('click',event=>{if(!event.target.closest('[data-home-id]')){doc.querySelectorAll('.home-selected').forEach(x=>x.classList.remove('home-selected'));$('homepageTextToolbar').classList.add('hidden');}});win.scrollTo(0,y);
  }
  function decorateCard(card){
    const doc=card.ownerDocument,move=doc.createElement('span'),resize=doc.createElement('span');move.className='home-drag-handle';move.textContent='MOVE';resize.className='home-resize-handle';resize.title='Drag to resize';card.append(move,resize);
    card.addEventListener('click',event=>{if(event.target.closest('[data-home-field],.home-drag-handle,.home-resize-handle'))return;event.stopPropagation();selectNode(card);});
    move.addEventListener('pointerdown',event=>startMove(event,card));resize.addEventListener('pointerdown',event=>startResize(event,card));
  }
  function startMove(event,card){
    event.preventDefault();event.stopPropagation();const doc=card.ownerDocument,section=card.dataset.homeSection;card.classList.add('home-dragging');event.target.setPointerCapture?.(event.pointerId);let target=null;
    const move=e=>{const found=doc.elementFromPoint(e.clientX,e.clientY)?.closest?.(`[data-home-section="${section}"]`);if(found&&found!==card)target=found;};
    const end=()=>{card.classList.remove('home-dragging');doc.removeEventListener('pointermove',move);doc.removeEventListener('pointerup',end);if(!target)return;const a=findItem(card.dataset.homeId),b=findItem(target.dataset.homeId);if(!a||!b)return;const order=a.sort_order;a.sort_order=b.sort_order;b.sort_order=order;normalize();markDirty('Card moved. Publish when ready.');renderCanvas();};
    doc.addEventListener('pointermove',move);doc.addEventListener('pointerup',end,{once:true});
  }
  function startResize(event,card){
    event.preventDefault();event.stopPropagation();const doc=card.ownerDocument,item=findItem(card.dataset.homeId);if(!item)return;const startX=event.clientX,startY=event.clientY,start=card.getBoundingClientRect(),parent=card.parentElement,columns=Math.max(1,doc.defaultView.getComputedStyle(parent).gridTemplateColumns.split(' ').length),columnWidth=parent.getBoundingClientRect().width/columns;event.target.setPointerCapture?.(event.pointerId);
    const move=e=>{const width=Math.max(1,Math.min(columns,Math.round((start.width+e.clientX-startX)/columnWidth)));const height=Math.max(70,Math.round(start.height+e.clientY-startY));item.style_data={...(item.style_data||{}),width,min_height:height};card.style.setProperty('--home-span',width);card.style.minHeight=`${height}px`;};
    const end=()=>{doc.removeEventListener('pointermove',move);doc.removeEventListener('pointerup',end);markDirty('Card resized. Publish when ready.');selectNode(card);};doc.addEventListener('pointermove',move);doc.addEventListener('pointerup',end,{once:true});
  }
  function applyStyle(kind,value){if(!selectedItem||!selectedNode?.dataset.homeField)return;const field=selectedNode.dataset.homeField,key=styleKey(selectedItem,field,kind);selectedItem.style_data={...(selectedItem.style_data||{})};if(value)selectedItem.style_data[key]=value;else delete selectedItem.style_data[key];if(kind==='font_size')selectedNode.style.fontSize=value?`${value}px`:'';else selectedNode.style.color=value||'';markDirty();}
  function openEditor(){
    $('homepageItemDialogTitle').textContent='Add to Homepage';$('homepageItemId').value=newId();$('homepageItemType').value='card';$('homepageItemSection').value='dashboard';$('homepageItemTitle').value='';$('homepageItemBody').value='';$('homepageItemIcon').value='';$('homepageItemUrl').value='';$('homepageItemLinkLabel').value='';$('homepageItemNewTab').checked=false;$('homepageItemMsg').textContent='';updateDialogFields();$('homepageItemDialog').showModal();
  }
  function updateDialogFields(){const link=$('homepageItemType').value==='link';$('homepageItemSection').value=link?'navigation':($('homepageItemSection').value==='navigation'?'dashboard':$('homepageItemSection').value);$('homepageItemSection').disabled=link;$('homepageItemBodyRow').classList.toggle('hidden',link);$('homepageItemIconRow').classList.toggle('hidden',link);$('homepageItemLinkLabelRow').classList.toggle('hidden',link);}
  function addItem(event){event.preventDefault();const title=$('homepageItemTitle').value.trim();if(!title){$('homepageItemMsg').textContent='Enter a title.';return;}const type=$('homepageItemType').value,section=type==='link'?'navigation':$('homepageItemSection').value;items.push({_draftId:$('homepageItemId').value,item_type:type,section_key:section,item_key:null,title,body:$('homepageItemBody').value.trim(),url:$('homepageItemUrl').value.trim(),icon:$('homepageItemIcon').value.trim(),link_label:$('homepageItemLinkLabel').value.trim(),sort_order:999,active:true,open_new_tab:$('homepageItemNewTab').checked,style_data:{}});normalize();$('homepageItemDialog').close();markDirty('Item added. Publish when ready.');renderCanvas();}
  async function publish(){try{normalize();$('homepageMsg').textContent='Publishing homepage…';$('publishHomepage').disabled=true;const payload=items.map(({_draftId,id,company_id,created_at,updated_at,created_by,updated_by,...item})=>item),{error}=await s.rpc('publish_homepage_content',{p_items:payload});if(error)throw error;dirty=false;await load();$('homepageMsg').textContent='Published. The live homepage now matches this canvas.';}catch(error){$('homepageMsg').textContent=error.message;}finally{$('publishHomepage').disabled=false;}}
  async function restore(){const id=$('homepageVersion').value;if(!id)return;$('homepageMsg').textContent='Restoring version…';const {error}=await s.rpc('restore_homepage_version',{p_version_id:id});if(error){$('homepageMsg').textContent=error.message;return;}await load();$('homepageMsg').textContent='Previous version restored and published.';}
  async function load(){try{await context();$('homepageMsg').textContent='Loading the live homepage canvas…';const [content,history]=await Promise.all([s.from('homepage_content').select('*').eq('company_id',company.id).order('section_key').order('sort_order'),s.from('homepage_versions').select('id,created_at').eq('company_id',company.id).order('created_at',{ascending:false}).limit(20)]);if(content.error)throw content.error;if(history.error)throw history.error;items=(content.data||[]).map(x=>({...x,style_data:x.style_data||{},_draftId:x.id||newId()}));versions=history.data||[];$('homepageVersion').innerHTML='<option value="">Choose a previous version</option>'+versions.map(x=>`<option value="${x.id}">${new Date(x.created_at).toLocaleString()}</option>`).join('');dirty=false;$('homepageMsg').textContent='Click directly on text or use the purple controls on a card.';renderCanvas(false);}catch(error){$('homepageMsg').textContent=error.message;}}
  function frameLoaded(){frameReady=true;renderCanvas(false);setTimeout(()=>renderCanvas(false),400);}
  function show(){document.querySelectorAll('.view').forEach(x=>x.classList.add('hidden'));$('homepage').classList.remove('hidden');document.querySelectorAll('nav [data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view==='homepage'));$('title').textContent='Visual Homepage Editor';load();}
  document.querySelector('nav [data-view="homepage"]')?.addEventListener('click',show);$('homepageCanvas').addEventListener('load',frameLoaded);$('addHomepageCard').onclick=openEditor;$('publishHomepage').onclick=publish;$('restoreHomepage').onclick=restore;$('homepageItemType').onchange=updateDialogFields;$('homepageItemForm').onsubmit=addItem;$('cancelHomepageItem').onclick=()=>$('homepageItemDialog').close();
  document.querySelectorAll('[data-canvas-size]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-canvas-size]').forEach(x=>x.classList.toggle('active',x===button));$('homepageCanvasShell').className=`homepage-canvas-shell ${button.dataset.canvasSize}`;});
  $('homepageFontSize').oninput=event=>applyStyle('font_size',Math.max(10,Math.min(120,Number(event.target.value)||16)));$('homepageFontColor').oninput=event=>applyStyle('color',event.target.value);$('homepageResetStyle').onclick=()=>{applyStyle('font_size',null);applyStyle('color',null);selectNode(selectedNode);};
  $('homepageEditLink').onclick=()=>{if(!selectedItem)return;const next=prompt('Link address',selectedItem.url||'');if(next===null)return;selectedItem.url=next.trim();markDirty('Link changed. Publish when ready.');renderCanvas();};
  $('homepageHideItem').onclick=()=>{if(!selectedItem)return;selectedItem.active=selectedItem.active===false;markDirty(selectedItem.active?'Item will be shown.':'Item will be hidden.');renderCanvas();};
  $('homepageDeleteItem').onclick=()=>{if(!selectedItem||!confirm(`Delete “${selectedItem.title||'this item'}” from the draft?`))return;items=items.filter(x=>x!==selectedItem);normalize();markDirty('Item deleted from the draft. Publish when ready.');renderCanvas();};
  window.addEventListener('beforeunload',event=>{if(!dirty)return;event.preventDefault();event.returnValue='';});
})();
