(() => {
  'use strict';
  const s=window.FP365_ADMIN_CLIENT;if(!s)return;
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const sections={features:'Feature Strip',resources:'Resource Cards',dashboard:'Dashboard Cards',mobile:'Mobile / Access Cards',documents:'Document Cards',navigation:'Top Navigation Links'};
  const heroKeys=['hero_eyebrow','hero_title','hero_accent','hero_body','hero_button'];
  let profile,company,items=[],versions=[];

  async function context(){if(profile&&company)return;const {data:session}=await s.auth.getSession(),user=session.session?.user;if(!user)throw new Error('Admin session is unavailable.');const {data,error}=await s.from('employee_profiles').select('*,companies(*)').eq('id',user.id).single();if(error)throw error;profile=data;company=Array.isArray(data.companies)?data.companies[0]:data.companies;if(!company?.id)throw new Error('Company record not found.');}
  const byKey=key=>items.find(x=>x.item_key===key);
  function heroItem(key){let item=byKey(key);if(!item){item={item_type:'text',section_key:'hero',item_key:key,title:'',body:'',url:'',sort_order:(heroKeys.indexOf(key)+1)*10,active:true,open_new_tab:false};items.push(item);}return item;}
  function readHero(){const pairs={hero_eyebrow:['homepageEyebrow'],hero_title:['homepageTitle','homepageTitleLine2'],hero_accent:['homepageAccent'],hero_body:['homepageDescription'],hero_button:['homepageButtonLabel',null,'homepageButtonUrl']};Object.entries(pairs).forEach(([key,ids])=>{const item=heroItem(key);item.title=$(ids[0]).value.trim();if(ids[1])item.body=$(ids[1]).value.trim();if(ids[2])item.url=$(ids[2]).value.trim();});}
  function fillHero(){const set=(id,value)=>{$(id).value=value||'';};let x=heroItem('hero_eyebrow');set('homepageEyebrow',x.title);x=heroItem('hero_title');set('homepageTitle',x.title);set('homepageTitleLine2',x.body);x=heroItem('hero_accent');set('homepageAccent',x.title);x=heroItem('hero_body');set('homepageDescription',x.title);x=heroItem('hero_button');set('homepageButtonLabel',x.title);set('homepageButtonUrl',x.url);}
  function render(){fillHero();const list=$('homepageItems');const rows=items.filter(x=>x.item_type!=='text').sort((a,b)=>Object.keys(sections).indexOf(a.section_key)-Object.keys(sections).indexOf(b.section_key)||a.sort_order-b.sort_order);list.innerHTML=rows.length?rows.map((item,index)=>`<article class="homepage-editor-item${item.active?'':' content-item-inactive'}"><div><h3>${esc(item.icon?`${item.icon} ${item.title}`:item.title)}</h3><p>${esc(item.body||item.url||'')}</p><small>${esc(sections[item.section_key]||item.section_key)} · ${item.item_type==='link'?'Link':'Card'} · ${item.active?'Visible':'Hidden'}</small></div><div class="homepage-editor-actions"><button type="button" data-home-move="up" data-home-index="${index}">↑</button><button type="button" data-home-move="down" data-home-index="${index}">↓</button><button type="button" data-home-edit="${esc(item._draftId)}">Edit</button><button type="button" class="danger" data-home-delete="${esc(item._draftId)}">Delete</button></div></article>`).join(''):'<p class="homepage-editor-empty">No cards or links have been added.</p>';}
  function normalize(){let counters={};items.forEach(item=>{if(item.item_type==='text')return;counters[item.section_key]=(counters[item.section_key]||0)+10;item.sort_order=counters[item.section_key];});}
  function newId(){return crypto.randomUUID?crypto.randomUUID():`draft-${Date.now()}-${Math.random()}`;}
  function openEditor(item){const isNew=!item;item=item||{_draftId:newId(),item_type:'card',section_key:'dashboard',title:'',body:'',url:'',icon:'',link_label:'',active:true,open_new_tab:false,sort_order:999};$('homepageItemDialogTitle').textContent=isNew?'Add Homepage Item':'Edit Homepage Item';$('homepageItemId').value=item._draftId;$('homepageItemType').value=item.item_type;$('homepageItemSection').value=item.section_key;$('homepageItemTitle').value=item.title||'';$('homepageItemBody').value=item.body||'';$('homepageItemIcon').value=item.icon||'';$('homepageItemUrl').value=item.url||'';$('homepageItemLinkLabel').value=item.link_label||'';$('homepageItemActive').checked=item.active!==false;$('homepageItemNewTab').checked=!!item.open_new_tab;$('homepageItemMsg').textContent='';updateDialogFields();$('homepageItemDialog').showModal();}
  function updateDialogFields(){const link=$('homepageItemType').value==='link';$('homepageItemSection').value=link?'navigation':($('homepageItemSection').value==='navigation'?'dashboard':$('homepageItemSection').value);$('homepageItemSection').disabled=link;$('homepageItemBodyRow').classList.toggle('hidden',link);$('homepageItemIconRow').classList.toggle('hidden',link);$('homepageItemLinkLabelRow').classList.toggle('hidden',link);}
  function saveItem(event){event.preventDefault();const id=$('homepageItemId').value,title=$('homepageItemTitle').value.trim();if(!title)return $('homepageItemMsg').textContent='Enter a title or link label.';let item=items.find(x=>x._draftId===id);if(!item){item={_draftId:id};items.push(item);}Object.assign(item,{item_type:$('homepageItemType').value,section_key:$('homepageItemType').value==='link'?'navigation':$('homepageItemSection').value,title,body:$('homepageItemBody').value.trim(),icon:$('homepageItemIcon').value.trim(),url:$('homepageItemUrl').value.trim(),link_label:$('homepageItemLinkLabel').value.trim(),active:$('homepageItemActive').checked,open_new_tab:$('homepageItemNewTab').checked});normalize();$('homepageItemDialog').close();render();}
  function move(index,direction){const rows=items.filter(x=>x.item_type!=='text').sort((a,b)=>Object.keys(sections).indexOf(a.section_key)-Object.keys(sections).indexOf(b.section_key)||a.sort_order-b.sort_order),item=rows[index],same=rows.filter(x=>x.section_key===item.section_key),at=same.indexOf(item),swap=same[at+(direction==='up'?-1:1)];if(!swap)return;const a=items.indexOf(item),b=items.indexOf(swap);[items[a],items[b]]=[items[b],items[a]];normalize();render();}
  function safeUrl(value){const url=String(value||'').trim();return /^(https?:|mailto:|tel:|#)/i.test(url)?url:'';}
  function preview(){readHero();const hero={eyebrow:byKey('hero_eyebrow'),title:byKey('hero_title'),accent:byKey('hero_accent'),body:byKey('hero_body')},rows=items.filter(x=>x.item_type==='card'&&x.active);$('homepagePreviewBody').innerHTML=`<div class="homepage-preview-frame"><div class="homepage-preview-hero"><small>${esc(hero.eyebrow?.title)}</small><h2>${esc(hero.title?.title)}<span>${esc(hero.title?.body)} ${esc(hero.accent?.title)}</span></h2><p>${esc(hero.body?.title)}</p></div><div class="homepage-preview-sections">${Object.entries(sections).filter(([key])=>key!=='navigation').map(([key,label])=>{const cards=rows.filter(x=>x.section_key===key);return cards.length?`<section><h3>${esc(label)}</h3><div class="homepage-preview-grid">${cards.map(x=>`<article class="homepage-preview-card"><b>${esc(x.icon||'')}</b><h4>${esc(x.title)}</h4><p>${esc(x.body||'')}</p>${safeUrl(x.url)?`<a href="${esc(safeUrl(x.url))}" target="_blank" rel="noopener">${esc(x.link_label||'Open link')}</a>`:''}</article>`).join('')}</div></section>`:'';}).join('')}</div></div>`;$('homepagePreviewDialog').showModal();}
  async function publish(){try{readHero();normalize();$('homepageMsg').textContent='Publishing homepage…';$('publishHomepage').disabled=true;const payload=items.map(({_draftId,id,created_at,updated_at,...item})=>item);const {error}=await s.rpc('publish_homepage_content',{p_items:payload});if(error)throw error;await load();$('homepageMsg').textContent='Published. The public homepage is now updated.';}catch(error){$('homepageMsg').textContent=error.message;}finally{$('publishHomepage').disabled=false;}}
  async function restore(){const id=$('homepageVersion').value;if(!id)return;$('homepageMsg').textContent='Restoring version…';const {error}=await s.rpc('restore_homepage_version',{p_version_id:id});if(error)return $('homepageMsg').textContent=error.message;await load();$('homepageMsg').textContent='Previous version restored and published.';}
  async function load(){try{await context();$('homepageMsg').textContent='Loading homepage…';const [content,history]=await Promise.all([s.from('homepage_content').select('*').eq('company_id',company.id).order('section_key').order('sort_order'),s.from('homepage_versions').select('id,created_at').eq('company_id',company.id).order('created_at',{ascending:false}).limit(20)]);if(content.error)throw content.error;if(history.error)throw history.error;items=(content.data||[]).map(x=>({...x,_draftId:x.id||newId()}));versions=history.data||[];$('homepageVersion').innerHTML='<option value="">Choose a previous version</option>'+versions.map(x=>`<option value="${esc(x.id)}">${esc(new Date(x.created_at).toLocaleString())}</option>`).join('');$('homepageMsg').textContent='';render();}catch(error){$('homepageMsg').textContent=error.message;}}
  function show(){document.querySelectorAll('.view').forEach(x=>x.classList.add('hidden'));$('homepage').classList.remove('hidden');document.querySelectorAll('nav [data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view==='homepage'));$('title').textContent='Homepage Editor';load();}
  document.querySelector('nav [data-view="homepage"]')?.addEventListener('click',show);
  $('addHomepageCard').onclick=()=>openEditor();$('previewHomepage').onclick=preview;$('publishHomepage').onclick=publish;$('restoreHomepage').onclick=restore;$('homepageItemType').onchange=updateDialogFields;$('homepageItemForm').onsubmit=saveItem;$('cancelHomepageItem').onclick=()=>$('homepageItemDialog').close();$('closeHomepagePreview').onclick=()=>$('homepagePreviewDialog').close();
  $('homepageItems').onclick=event=>{const edit=event.target.closest('[data-home-edit]'),del=event.target.closest('[data-home-delete]'),moveButton=event.target.closest('[data-home-move]');if(edit)openEditor(items.find(x=>x._draftId===edit.dataset.homeEdit));if(del&&confirm('Remove this item from the homepage draft?')){items=items.filter(x=>x._draftId!==del.dataset.homeDelete);normalize();render();}if(moveButton)move(Number(moveButton.dataset.homeIndex),moveButton.dataset.homeMove);};
})();
