(() => {
const cfg=window.FP365_CONFIG||{};
const ready=cfg.supabaseUrl&&!cfg.supabaseUrl.includes("PASTE_")&&cfg.supabasePublishableKey&&!cfg.supabasePublishableKey.includes("PASTE_");
const screens=[...document.querySelectorAll(".screen")],homeButton=document.getElementById("homeButton");
let sb=null,profile=null,gps=null;
function show(id){screens.forEach(s=>s.classList.toggle("hidden",s.id!==id));homeButton.classList.toggle("hidden",id==="loginScreen"||id==="setupScreen"||id==="homeScreen");window.scrollTo(0,0)}
function msg(id,text,error=false){const e=document.getElementById(id);e.textContent=text;e.className="message "+(error?"error":"success")}
if(!ready){show("setupScreen");return}
sb=supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
async function loadProfile(uid){const{data,error}=await sb.from("employee_profiles").select("*").eq("id",uid).single();if(error)throw error;profile=data;document.getElementById("sessionLabel").textContent=`${data.full_name} · ${data.role}`;document.getElementById("welcome").textContent=`Welcome, ${data.full_name}`;document.getElementById("profileSummary").innerHTML=`<b>${data.full_name}</b><br>Employee ID: ${data.employee_id}<br>Role: ${data.role}<br>Status: ${data.status}`}
async function loadTrucks(){const{data,error}=await sb.from("trucks").select("id,truck_number,status").eq("company_id",profile.company_id).eq("status","active").is("deleted_at",null).order("truck_number");if(error)throw error;document.getElementById("truck").innerHTML='<option value="">Select truck</option>'+data.map(t=>`<option value="${t.id}" data-number="${t.truck_number}">${t.truck_number}</option>`).join("")}
async function boot(){const{data}=await sb.auth.getSession();if(!data.session)return show("loginScreen");try{await loadProfile(data.session.user.id);await loadTrucks();show("homeScreen")}catch(e){await sb.auth.signOut();msg("loginMessage",e.message,true);show("loginScreen")}}
document.getElementById("loginButton").onclick=async()=>{msg("loginMessage","Signing in...");const email=document.getElementById("email").value.trim(),password=document.getElementById("password").value;const{data,error}=await sb.auth.signInWithPassword({email,password});if(error)return msg("loginMessage",error.message,true);try{await loadProfile(data.user.id);await loadTrucks();show("homeScreen")}catch(e){await sb.auth.signOut();msg("loginMessage",e.message,true)}};
document.getElementById("forgotButton").onclick=async()=>{const email=document.getElementById("email").value.trim();if(!email)return msg("loginMessage","Enter your email first.",true);const{error}=await sb.auth.resetPasswordForEmail(email,{redirectTo:location.href.split("?")[0]});msg("loginMessage",error?error.message:"Password reset email requested.",!!error)};
document.querySelectorAll(".menu-button").forEach(b=>b.onclick=async()=>{if(b.dataset.target)return show(b.dataset.target);if(b.dataset.action==="profile"){document.getElementById("profileDetails").innerHTML=`<b>${profile.full_name}</b><br>Employee ID: ${profile.employee_id}<br>Email: ${profile.email}<br>Phone: ${profile.phone||"Not entered"}<br>Title: ${profile.title||profile.role}<br>DL: ${profile.drivers_license_number||"Not entered"}<br>State: ${profile.drivers_license_state||"Not entered"}<br>DL Expiration: ${profile.drivers_license_expires||"Not entered"}<br>Medical Card: ${profile.medical_card_expires||"N/A"}`;return show("profileScreen")}if(b.dataset.action==="viewEntries"){const{data,error}=await sb.from("inspections").select("id,inspection_number,equipment_type,status,truck_number,location_from,location_to,started_at").eq("driver_id",profile.id).order("started_at",{ascending:false});document.getElementById("entriesList").innerHTML=error?`<div class="notice error">${error.message}</div>`:!data.length?'<div class="notice">No entries yet.</div>':data.map(i=>`<div class="entry"><b>${i.inspection_number||"Draft inspection"}</b><br>${i.equipment_type} · ${i.status}<br>Truck ${i.truck_number}<br>${i.location_from} → ${i.location_to}<br><span class="muted">${new Date(i.started_at).toLocaleString()}</span></div>`).join("");return show("entriesScreen")}if(b.dataset.action==="logout"){await sb.auth.signOut();profile=null;document.getElementById("sessionLabel").textContent="Not signed in";show("loginScreen")}});
homeButton.onclick=()=>show("homeScreen");
document.getElementById("gpsButton").onclick=()=>{const s=document.getElementById("gpsStatus");if(!navigator.geolocation)return s.textContent="GPS not supported.";s.textContent="Capturing GPS...";navigator.geolocation.getCurrentPosition(p=>{gps={latitude:+p.coords.latitude.toFixed(6),longitude:+p.coords.longitude.toFixed(6)};s.textContent=`GPS captured: ${gps.latitude}, ${gps.longitude}`},e=>{gps=null;s.textContent=`GPS unavailable: ${e.message}`},{enableHighAccuracy:true,timeout:10000,maximumAge:0})};
document.getElementById("saveDraftButton").onclick=async()=>{const ids=["equipmentType","truck","trailer1","dolly","trailer2","locationFrom","locationTo","notes"],v=Object.fromEntries(ids.map(id=>[id,document.getElementById(id).value.trim()]));if(ids.some(id=>!v[id]))return msg("inspectionMessage","Complete every field. Use N/A where appropriate.",true);const sel=document.getElementById("truck"),num=sel.options[sel.selectedIndex].dataset.number;const payload={company_id:profile.company_id,driver_id:profile.id,truck_id:v.truck,equipment_type:v.equipmentType,status:"draft",truck_number:num,trailer_1_number:v.trailer1,dolly_number:v.dolly,trailer_2_number:v.trailer2,location_from:v.locationFrom,location_to:v.locationTo,notes:v.notes,start_latitude:gps?.latitude??null,start_longitude:gps?.longitude??null,gps_start_status:gps?"captured":"unavailable",created_by:profile.id,updated_by:profile.id};msg("inspectionMessage","Saving...");const{data,error}=await sb.from("inspections").insert(payload).select("id").single();msg("inspectionMessage",error?error.message:`Draft saved successfully. ID: ${data.id}`,!!error)};
if("serviceWorker"in navigator)navigator.serviceWorker.register("./service-worker.js").catch(console.error);
boot();
})();