(() => {
const cfg=window.FP365_CONFIG||{};
const ready=cfg.supabaseUrl&&!cfg.supabaseUrl.includes("PASTE_")&&cfg.supabasePublishableKey&&!cfg.supabasePublishableKey.includes("PASTE_");
const screens=[...document.querySelectorAll(".screen")],back=document.getElementById("backButton"),home=document.getElementById("homeButton");
let sb,profile,entries=[],history=["loginScreen"];
function show(id,push=true){screens.forEach(s=>s.classList.toggle("hidden",s.id!==id));const logged=!["loginScreen","setupScreen"].includes(id);home.classList.toggle("hidden",!logged||id==="homeScreen");back.classList.toggle("hidden",!logged||id==="homeScreen");if(push&&history.at(-1)!==id)history.push(id);scrollTo(0,0)}
function goHome(){history=["homeScreen"];show("homeScreen",false)}
function goBack(){if(history.length<=1)return goHome();history.pop();show(history.at(-1),false)}
function msg(id,t,e=false){const x=document.getElementById(id);x.textContent=t;x.className="message "+(e?"error":"success")}
function safe(v){return v??"N/A"}function rtype(v){return {"53_trailer":"53' Trailer","single_pup":"Single Pup","doubles":"Doubles","bobtail":"Bobtail"}[v]||v}
if(!ready){show("setupScreen",false);return}
sb=supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
async function loadProfile(uid){const{data,error}=await sb.from("employee_profiles").select("*").eq("id",uid).single();if(error)throw error;profile=data;sessionLabel.textContent=`${data.full_name} · ${data.role}`;welcome.textContent=`Welcome, ${data.full_name}`;profileSummary.innerHTML=`<b>${data.full_name}</b><br>Employee ID: ${data.employee_id}<br>Role: ${data.role}<br>Status: ${data.status}`}
async function boot(){const{data}=await sb.auth.getSession();if(!data.session)return show("loginScreen",false);await loadProfile(data.session.user.id);show("homeScreen",false)}
async function loadEntries(){const{data,error}=await sb.from("inspections").select("*").eq("driver_id",profile.id).order("started_at",{ascending:false});if(error)throw error;entries=data||[];entriesList.innerHTML=!entries.length?'<div class="notice">No entries yet.</div>':entries.map((i,n)=>`<div class="entry" data-i="${n}"><div class="entry-number">${i.inspection_number}</div><div>${rtype(i.equipment_type)} · ${i.status}</div><div>Truck ${i.truck_number}</div><div>${i.location_from} → ${i.location_to}</div></div>`).join("");entriesList.querySelectorAll(".entry").forEach(e=>e.onclick=()=>openEntry(entries[+e.dataset.i]))}
async function openEntry(i){entryDetails.innerHTML=`<div class="detail-grid"><b>Entry</b><span>${safe(i.inspection_number)}</span><b>Status</b><span>${safe(i.status)}</span><b>Equipment</b><span>${rtype(i.equipment_type)}</span><b>Truck</b><span>${safe(i.truck_number)}</span><b>Trailer 1</b><span>${safe(i.trailer_1_number)}</span><b>Dolly</b><span>${safe(i.dolly_number)}</span><b>Trailer 2</b><span>${safe(i.trailer_2_number)}</span><b>From</b><span>${safe(i.location_from)}</span><b>To</b><span>${safe(i.location_to)}</span><b>Notes</b><span>${safe(i.notes)}</span></div>`;const{data}=await sb.from("inspection_photos").select("*").eq("inspection_id",i.id).is("deleted_at",null);const photos=[];for(const p of data||[]){const s=await sb.storage.from("inspection-photos").createSignedUrl(p.storage_path,3600);if(s.data?.signedUrl)photos.push({...p,url:s.data.signedUrl})}entryPhotos.innerHTML=photos.map(p=>`<div class="photo"><b>${p.photo_label||"Photo"}</b><img src="${p.url}"></div>`).join("");show("entryDetailScreen")}
function renderProfile(){profileDetails.innerHTML=`<div class="detail-grid"><b>Full Name</b><span>${safe(profile.full_name)}</span><b>Phone</b><span>${safe(profile.phone)}</span><b>Employee ID</b><span>${safe(profile.employee_id)}</span><b>Email</b><span>${safe(profile.email)}</span><b>Title</b><span>${safe(profile.title||profile.role)}</span></div>`}
async function todayInspections(){const start=new Date();start.setHours(0,0,0,0);const end=new Date(start);end.setDate(end.getDate()+1);const{data,error}=await sb.from("inspections").select("*").eq("driver_id",profile.id).eq("status","verified").gte("submitted_at",start.toISOString()).lt("submitted_at",end.toISOString()).order("submitted_at");if(error)throw error;return data||[]}
async function photosForInspection(id){const{data}=await sb.from("inspection_photos").select("*").eq("inspection_id",id).is("deleted_at",null).order("captured_at");const out=[];for(const p of data||[]){const s=await sb.storage.from("inspection-photos").createSignedUrl(p.storage_path,3600);if(s.data?.signedUrl)out.push({...p,url:s.data.signedUrl})}return out}
async function imageToDataUrl(url){const blob=await fetch(url).then(r=>r.blob());return await new Promise((res,rej)=>{const fr=new FileReader();fr.onload=()=>res(fr.result);fr.onerror=rej;fr.readAsDataURL(blob)})}
async function generatePdf(inspections){const{jsPDF}=window.jspdf;const doc=new jsPDF({unit:"pt",format:"letter"}),m=42,w=612,h=792;let y=50;const add=(t,s=10,b=false)=>{doc.setFont("helvetica",b?"bold":"normal");doc.setFontSize(s);const lines=doc.splitTextToSize(String(t),w-m*2);if(y+lines.length*(s+3)>h-50){doc.addPage();y=50}doc.text(lines,m,y);y+=lines.length*(s+3)+4};add("FLEET PROTECT 365",18,true);add("Wade Freight Systems",11,true);add(`Driver: ${profile.full_name} | Employee ID: ${profile.employee_id}`);add(`Date: ${new Date().toLocaleDateString()}`);y+=8;for(const i of inspections){add(i.inspection_number,14,true);add(`${rtype(i.equipment_type)} | Truck ${i.truck_number}`);add(`Trailer 1: ${safe(i.trailer_1_number)} | Dolly: ${safe(i.dolly_number)} | Trailer 2: ${safe(i.trailer_2_number)}`);add(`From: ${safe(i.location_from)}  To: ${safe(i.location_to)}`);add(`Started: ${new Date(i.started_at).toLocaleString()}`);add(`Submitted: ${new Date(i.submitted_at).toLocaleString()}`);add(`GPS Start: ${safe(i.start_latitude)}, ${safe(i.start_longitude)}`);add(`GPS Submit: ${safe(i.submit_latitude)}, ${safe(i.submit_longitude)}`);add(`Notes: ${safe(i.notes)}`);add("Driver certified this inspection as complete and accurate.",9,true);for(const p of await photosForInspection(i.id)){if(y>520){doc.addPage();y=50}add(p.photo_label||"Photo",10,true);try{const d=await imageToDataUrl(p.url),pr=doc.getImageProperties(d),scale=Math.min((w-m*2)/pr.width,260/pr.height),iw=pr.width*scale,ih=pr.height*scale;doc.addImage(d,pr.fileType,m,y,iw,ih,undefined,"MEDIUM");y+=ih+14}catch{add("Photo could not be embedded.",9)}}y+=16}return doc.output("arraybuffer")}
async function invokeEndShift(buffer,list){const bytes=new Uint8Array(buffer);let binary="";for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));const pdfBase64=btoa(binary),fileName=`${new Date().toISOString().slice(0,10)}_End_of_Shift_${profile.full_name.replace(/\s+/g,"_")}.pdf`;const{data,error}=await sb.functions.invoke("end-shift",{body:{pdfBase64,fileName,inspectionIds:list.map(i=>i.id)}});if(error)throw error;return data}
async function showEndShift(){show("endShiftScreen");const list=await todayInspections();endShiftList.innerHTML=list.length?list.map(i=>`<div class="entry"><div class="entry-number">${i.inspection_number}</div><div>${rtype(i.equipment_type)} · Truck ${i.truck_number}</div><div>${i.location_from} → ${i.location_to}</div></div>`).join(""):'<div class="notice">No submitted inspections found for today.</div>';endShiftStatus.textContent=list.length?`${list.length} inspection(s) ready.`:"Nothing to generate.";generateEndShiftButton.disabled=!list.length;generateEndShiftButton.onclick=async()=>{try{endShiftStatus.textContent="Generating PDF…";const pdf=await generatePdf(list);endShiftStatus.textContent="Emailing and saving to Google Drive…";const r=await invokeEndShift(pdf,list);endShiftStatus.textContent=`Complete. Email: ${r.emailStatus}. Google Drive: ${r.driveStatus}.`;show("logoutChecklistScreen")}catch(e){endShiftStatus.textContent=`Error: ${e.message}`}}}
function showFeedback(){feedbackName.value=profile.full_name||"";feedbackCategory.value="";feedbackMessage.value="";feedbackCounter.textContent="0 / 750";feedbackStatus.textContent="";show("feedbackScreen")}
async function submitFeedback(){const name=feedbackName.value.trim(),category=feedbackCategory.value,message=feedbackMessage.value.trim();if(!name||!category||!message)return msg("feedbackStatus","Complete every field.",true);const{data,error}=await sb.from("feedback_submissions").insert({company_id:profile.company_id,user_id:profile.id,submitted_name:name,category,message,app_version:"1.1",device_info:navigator.userAgent}).select("id").single();if(error)return msg("feedbackStatus",error.message,true);const sent=await sb.functions.invoke("send-feedback",{body:{feedbackId:data.id}});if(sent.error)return msg("feedbackStatus","Saved, but email delivery failed.",true);msg("feedbackStatus","Thank you. Your feedback has been submitted successfully.");setTimeout(goHome,900)}
loginButton.onclick=async()=>{const{data,error}=await sb.auth.signInWithPassword({email:email.value.trim(),password:password.value});if(error)return msg("loginMessage",error.message,true);await loadProfile(data.user.id);show("homeScreen")};forgotButton.onclick=async()=>{const{error}=await sb.auth.resetPasswordForEmail(email.value.trim(),{redirectTo:location.href.split("?")[0]});msg("loginMessage",error?error.message:"Password reset email requested.",!!error)};document.querySelector('[data-action="viewEntries"]').onclick=async()=>{await loadEntries();show("entriesScreen")};document.querySelector('[data-action="profile"]').onclick=()=>{renderProfile();show("profileScreen")};document.querySelector('[data-action="feedback"]').onclick=showFeedback;document.querySelector('[data-action="endShift"]').onclick=showEndShift;document.querySelector('[data-action="logout"]').onclick=()=>show("logoutChecklistScreen");feedbackFooter.onclick=e=>{e.preventDefault();showFeedback()};feedbackMessage.oninput=()=>feedbackCounter.textContent=`${feedbackMessage.value.length} / 750`;submitFeedbackButton.onclick=submitFeedback;cancelFeedbackButton.onclick=goHome;doneEntryButton.onclick=goHome;finishLogoutButton.onclick=async()=>{if(![c1,c2,c3,c4].every(x=>x.checked))return msg("logoutMessage","All four items must be checked.",true);await sb.auth.signOut();msg("logoutMessage","Have a good night.");setTimeout(()=>show("loginScreen",false),900)};home.onclick=goHome;back.onclick=goBack;boot();
})();