(()=>{
  'use strict';
  const s=window.FP365_DRIVER_CLIENT;if(!s)return;
  let userId='',showing=false;
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  function install(){const actions=document.querySelector('.topbar-actions');if(!actions||document.getElementById('messageBell'))return;const bell=document.createElement('button');bell.id='messageBell';bell.className='icon-btn message-bell hidden';bell.type='button';bell.setAttribute('aria-label','App messages');bell.innerHTML='🔔<span id="messageBadge" class="message-badge" hidden>0</span>';actions.prepend(bell);bell.onclick=()=>poll(true);const dialog=document.createElement('dialog');dialog.id='appMessageDialog';dialog.className='app-message-dialog';document.body.appendChild(dialog);}
  async function poll(force=false){try{const {data:session}=await s.auth.getSession();userId=session.session?.user?.id||'';document.getElementById('messageBell')?.classList.toggle('hidden',!userId);if(!userId)return;const {data,error}=await s.rpc('get_my_app_messages');if(error)throw error;const now=Date.now(),rows=(data||[]).filter(x=>x.app_messages&&(!x.app_messages.expires_at||new Date(x.app_messages.expires_at).getTime()>now)).sort((a,b)=>new Date(a.app_messages.created_at)-new Date(b.app_messages.created_at));const badge=document.getElementById('messageBadge');if(badge){badge.textContent=String(rows.length);badge.hidden=!rows.length;}if(rows.length&&(force||!showing))show(rows[0]);}catch(error){console.warn('App messages unavailable:',error.message);}}
  async function show(row){if(showing)return;showing=true;const message=row.app_messages,dialog=document.getElementById('appMessageDialog'),canNotify='Notification'in window;dialog.innerHTML=`<div class="app-message-card ${esc(message.priority)}"><small>${new Date(message.created_at).toLocaleString()}</small><h2>${esc(message.title)}</h2><p>${esc(message.body)}</p><div class="app-message-reply"><label for="appMessageReply">Reply (optional)</label><textarea id="appMessageReply" maxlength="2000" placeholder="Type a reply to Admin"></textarea><small id="appMessageReplyStatus"></small></div><div class="app-message-actions">${message.link_url?`<a href="${esc(message.link_url)}" target="_blank" rel="noopener">Open Link</a>`:''}<button id="sendAppMessageReply" type="button">Send Reply</button><button id="ackAppMessage" type="button">Acknowledge</button></div>${canNotify&&Notification.permission==='default'?'<div class="app-message-actions"><button id="enableMessageAlerts" type="button">Enable Phone Alerts</button></div>':''}</div>`;dialog.showModal();const now=new Date().toISOString();await s.from('app_message_recipients').update({delivered_at:row.delivered_at||now,read_at:row.read_at||now}).eq('message_id',message.id).eq('recipient_id',userId);if(!row.delivered_at&&canNotify&&Notification.permission==='granted'){try{const registration=await navigator.serviceWorker?.ready;registration?registration.showNotification(message.title,{body:message.body,icon:'../logo.png',tag:`fp365-message-${message.id}`}):new Notification(message.title,{body:message.body});}catch(_){}}
    document.getElementById('enableMessageAlerts')?.addEventListener('click',async()=>{const permission=await Notification.requestPermission();if(permission==='granted')document.getElementById('enableMessageAlerts').textContent='Phone Alerts Enabled';});
    document.getElementById('sendAppMessageReply').onclick=async()=>{const button=document.getElementById('sendAppMessageReply'),body=document.getElementById('appMessageReply').value.trim(),status=document.getElementById('appMessageReplyStatus');try{if(!body)throw new Error('Type a reply first.');button.disabled=true;status.textContent='Sending reply…';const {error}=await s.from('app_message_replies').insert({message_id:message.id,author_id:userId,body});if(error)throw error;const {error:ackError}=await s.from('app_message_recipients').update({acknowledged_at:new Date().toISOString()}).eq('message_id',message.id).eq('recipient_id',userId);if(ackError)throw ackError;dialog.close();showing=false;setTimeout(()=>poll(false),100);}catch(error){status.textContent=error.message;button.disabled=false;}};
    document.getElementById('ackAppMessage').onclick=async()=>{const button=document.getElementById('ackAppMessage'),status=document.getElementById('appMessageReplyStatus');button.disabled=true;status.textContent='Recording acknowledgement…';const {error}=await s.from('app_message_recipients').update({acknowledged_at:new Date().toISOString()}).eq('message_id',message.id).eq('recipient_id',userId);if(error){button.disabled=false;status.textContent=error.message;return;}button.textContent='Acknowledged';status.textContent='Acknowledgement recorded. You may still reply.';};dialog.addEventListener('cancel',event=>event.preventDefault(),{once:true});}
  install();setTimeout(()=>poll(false),1200);setInterval(()=>poll(false),60000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)poll(false);});
})();
